---
title: "Introducing 3D ggplots with rayshader"
date: 2020-06-11
output: html_notebook
---

```{r}
library(rayshader)
library(ggplot2)
library(tidyverse)
```


```{r}
diamonds
```


```{r}
gg <-
  diamonds %>% 
  ggplot(aes(x, depth)) +
  stat_density_2d(aes(fill = stat(nlevel)), geom = "polygon", n = 100, bins = 10, contour = TRUE) +
  facet_wrap(clarity ~ .) +
  scale_fill_viridis_c(option = "A")
gg
```


```{r}
plot_gg(gg, multicore = TRUE, width = 5, height = 5, scale = 250)
render_snapshot()
```


```{r}
#Data from Social Security administration
death = read_csv("https://www.tylermw.com/data/death.csv", skip = 1)
meltdeath = reshape2::melt(death, id.vars = "Year")

meltdeath$age = as.numeric(meltdeath$variable)

deathgg = ggplot(meltdeath) +
  geom_raster(aes(x=Year,y=age,fill=value)) +
  scale_x_continuous("Year",expand=c(0,0),breaks=seq(1900,2010,10)) +
  scale_y_continuous("Age",expand=c(0,0),breaks=seq(0,100,10),limits=c(0,100)) +
  scale_fill_viridis_c("Death\nProbability\nPer Year",trans = "log10",breaks=c(1,0.1,0.01,0.001,0.0001), labels = c("1","1/10","1/100","1/1000","1/10000")) +
  ggtitle("Death Probability vs Age and Year for the USA") +
  labs(caption = "Data Source: US Dept. of Social Security")

plot_gg(deathgg, multicore=TRUE,height=5,width=6,scale=500)
```



```{r}
# library(sf)
# 
# nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
# gg_nc = ggplot(nc) +
#   geom_sf(aes(fill = AREA)) +
#   scale_fill_viridis_c("Area") +
#   ggtitle("Area of counties in North Carolina") +
#   theme_bw()
# 
# plot_gg(gg_nc, multicore = TRUE, width = 6 ,height=2.7, fov = 70)
# render_depth(focallength=100,focus=0.72)
```


```{r}
a = data.frame(x=rnorm(20000, 10, 1.9), y=rnorm(20000, 10, 1.2) )
b = data.frame(x=rnorm(20000, 14.5, 1.9), y=rnorm(20000, 14.5, 1.9) )
c = data.frame(x=rnorm(20000, 9.5, 1.9), y=rnorm(20000, 15.5, 1.9) )
data = rbind(a,b,c)

#Lines
pp = ggplot(data, aes(x=x, y=y)) +
  geom_hex(bins = 20, size = 0.5, color = "black") +
  scale_fill_viridis_c(option = "C")
plot_gg(pp, width = 4, height = 4, scale = 300, multicore = TRUE)

#No lines
pp_nolines = ggplot(data, aes(x=x, y=y)) +
  geom_hex(bins = 20, size = 0) +
  scale_fill_viridis_c(option = "C")
plot_gg(pp_nolines, width = 4, height = 4, scale = 300, multicore = TRUE)
```


```{r}
mtcars_gg = ggplot(mtcars) + 
  geom_point(aes(x=mpg,color=cyl,y=disp),size=2) +
  scale_color_continuous(limits=c(0,8)) +
  ggtitle("mtcars: Displacement vs mpg vs # of cylinders") +
  theme(title = element_text(size=8),
        text = element_text(size=12)) 

plot_gg(mtcars_gg, height=3, width=3.5, multicore=TRUE, pointcontract = 0.7, soliddepth=-200)
```





















