---
title: "R Notebook"
output: html_notebook
---
```{r}
require('rethinking')
```


```{r}
pos <- replicate(100000, sum(runif(1000, -1, 1)))
```

```{r}
hist(pos)
```

```{r}
plot(density(pos))
```

```{r}
growth <- replicate(1000000, prod(1 + runif(12, 0, 0.1)))
dens(growth, norm.comp = TRUE)
```

```{r}
big <- replicate(10000, prod(1 + runif(12, 0, 0.5)))
small <- replicate(10000, prod(1 + runif(12, 0, 0.01)))
log.big <- replicate(10000, log(prod(1 + runif(12, 0, 0.5))))
```

```{r}
data(Howell1)
d <- Howell1
d2 <- d[d$age >= 18, ]
```

```{r}
plot(height ~ weight, data = d2)
```
```{r}
curve(dnorm(x, 178, 20), from = 100, to=250)
curve(dunif(x, 0, 50), from = -10, to = 60)
```

```{r}
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h)
```


```{r}
mu.list <- seq(from = 140, to = 160, length.out = 200)
sigma.list <- seq(from = 4, to = 9, length.out = 200)
post <- expand.grid(mu = mu.list, sigma = sigma.list)
post$LL <- sapply(1:nrow(post), function(i) sum(dnorm(d2$height, mean=post$mu[i], sd=post$sigma[i], log=TRUE)))
post$prod <- post$LL + dnorm(post$mu, 178, 20, TRUE) + dunif(post$sigma, 0, 50, TRUE)
post$prob <- exp(post$prod - max(post$prod))

contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)
```

```{r, fig.asp = 1}
sample.rows <- sample(1:nrow(post), size = 1e4, replace = TRUE, prob = post$prob)
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]
plot(sample.mu, sample.sigma, cex=4, pch=16, col = col.alpha(rangi2, 0.1))
```

```{r}
dens(sample.mu)
dens(sample.sigma)
```

```{r}
plot(d2$height ~ d2$weight)
```

```{r}
m4.3 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * weight,
    a ~ dnorm(156, 100),
    b ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
  ),
  data = d2
)
```

```{r}
precis(m4.3, corr = TRUE)
```

```{r}
d2$weight.c <- d2$weight - mean(d2$weight)

m4.4 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * weight.c,
    a ~ dnorm(178, 100),
    b ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
  ),
  data = d2
)
precis(m4.4, corr = TRUE)

```

```{r}
plot(height ~ weight, data = d2)
abline(a = coef(m4.3)["a"], b = coef(m4.3)["b"], col = 'red')
```

```{r}
post <- extract.samples(m4.3)
```

```{r}
N <- 300
dN <- d2[1:N, ]
mN <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * weight,
    a ~ dnorm(178, 100),
    b ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
  ),
  data = dN
)

post <- extract.samples(mN)
plot(dN$weight, dN$height,
     xlim = range(d2$weight), ylim = range(d2$height),
     col = rangi2, xlab = 'weight', ylab = 'height')
mtext(concat("N = ", N))
for(i in 1:20) {
  abline(a = post$a[i], b = post$b[i], col = col.alpha('black', 0.3))
}
```


```{r}
sim.height <- sim(m4.3, data = list(weight = weight.seq), n = 100000)
str(sim.height)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
height.HPDI <- apply(sim.height, 2, HPDI, prob = 0.89)
```

```{r}
plot(height ~ weight, d2, col = col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
shade(height.PI, weight.seq)
#shade(height.HPDI, weight.seq)
```

```{r}
d$weight.s <- (d$weight - mean(d$weight)) / sd(d$weight)
d$weight.s2 <- d$weight.s^2
m4.5 <- map(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1 * weight.s + b2 * weight.s2,
    a ~ dnorm(178, 100),
    b1 ~ dnorm(0, 10),
    b2 ~ dnorm(0, 10), 
    sigma ~ dunif(0, 50)
  ),
  data = d
)
```

```{r}
precis(m4.5)
weight.seq <- seq(from = -2.2, to = 2, length.out = 30)
pred_dat <- list(weight.s = weight.seq, weight.s2 = weight.seq ^ 2)
mu <- link(m4.5, data = pred_dat)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
sim.height <- sim(m4.5, data = pred_dat)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
```

```{r}
plot(height ~ weight.s, data = d, col = col.alpha(rangi2, 0.5), xaxt='n')
lines(weight.seq, mu.mean)
shade(mu.PI, weight.seq)
shade(height.PI, weight.seq)
at <- c(-2, -1, 0, 1, 2)
labels <- at * sd(d$weight) + mean(d$weight)
axis(side = 1, at = at, labels = round(labels, 1))
```



```{r}
mu0 <- 1.9
t20 <- 0.95 ^2
s20 <- .01
nu0 <- 1
y <- c(1.64, 1.70, 1.72, 1.74, 1.82, 1.82, 1.82, 1.90, 2.08)
G <- 100
H <- 100
mean.grid <- seq(1.505, 2.00, length = G)
prec.grid <- seq(1.75, 175, length = H)
post.grid <- matrix(nrow = G, ncol = H)
for (g in 1:G) {
  for (h in 1:H) {
    post.grid[g, h] <-
      dnorm(mean.grid[g], mu0, sqrt(t20)) * 
      dgamma(prec.grid[h], nu0 / 2, s20 * nu0 / 2) *
      prod(dnorm(y, mean.grid[g], 1/sqrt(prec.grid[h])))
  }
}
post.grid <- post.grid / sum(post.grid)
```


```{r}
data(reedfrogs)
d <- reedfrogs
str(d)

d$tank <- 1:nrow(d)
m12.1 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank] ~ dnorm(0, 5)
  ),
  data = d
)
precis(m12.1, depth = 2)
```

```{r}
m12.2 <- map2stan(
  alist(
    surv ~ dbinom(density, p),
    logit(p) <- a_tank[tank],
    a_tank[tank] ~ dnorm(a, sigma),
    a ~ dnorm(0, 1),
    sigma ~ dcauchy(0, 1)
  ),
  data = d, iter = 4000, chains = 4
)
precis(m12.2, depth = 2)
compare(m12.1, m12.2)
```




```{r}
a <- 3.5
b <- -1
sigma_a <- 1
sigma_b <- 0.5
rho <- -0.7
Mu <- c(a, b)
sigmas <- c(sigma_a, sigma_b)
Rho <- matrix(c(1, rho, rho, 1), nrow = 2)
Sigma <- diag(sigmas) %*% Rho %*% diag(sigmas)
N_cafes <- 100
set.seed(5)
vary_effects <- mvrnorm(N_cafes, Mu, Sigma)
a_cafe <- vary_effects[, 1]
b_cafe <- vary_effects[, 2]
plot(a_cafe, b_cafe, col = rangi2,
     xlab = 'intercepts (a_cafe)', 
     ylab = 'slopes (b_cafe)' )
library(ellipse)
for (l in c(0.1, 0.3, 0.5, 0.8, 0.99)) {
  lines(ellipse(Sigma, centre = Mu, level = l), col = col.alpha('black', 0.2))
}
```

```{r}
N_visits <- 100
afternoon <- rep(0:1, N_visits * N_cafes / 2)
cafe_id <- rep(1:N_cafes, each = N_visits)
mu <- a_cafe[cafe_id] + b_cafe[cafe_id] * afternoon
sigma <- 0.5
wait <- rnorm(N_visits * N_cafes, mu, sigma)
d <- data.frame(cafe = cafe_id, afternoon = afternoon, wait = wait)
```

```{r}
library(rethinking)
m13.1 <- map2stan(
  alist(
    wait ~ dnorm(mu, sigma),
    mu <- a_cafe[cafe] + b_cafe[cafe] * afternoon,
    c(a_cafe, b_cafe)[cafe] ~ dmvnorm2(c(a, b), sigma_cafe, Rho),
    a ~ dnorm(0, 10),
    b ~ dnorm(0, 10),
    sigma_cafe ~ dcauchy(0, 2),
    sigma ~ dcauchy(0, 2),
    Rho ~ dlkjcorr(2)
  ), data = d, iter = 5000, warmup = 2000, chains = 2
)
post <- extract.samples(m13.1)
```
