---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
d <-
  tibble(p_1 = 0, 
         p_2 = rep(1:0, times = c(1, 3)),
         p_3 = rep(1:0, times = c(2, 2)),
         p_4 = rep(1:0, times = c(3, 1)),
         p_5 = 1)
d
```

```{r}
d %>% 
  gather() %>%
  mutate(x = rep(1:4, time = 5), 
         possibility = rep(1:5, each = 4)) %>%
  ggplot(aes(x = x, y = possibility,
             fill = value %>% as.character())) +
  geom_point(shape = 21, size = 5) +
  scale_fill_manual(values = c("white", "navy")) +
  scale_x_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(.75, 4.24),
                  ylim = c(.75, 5.25)) +
  theme(legend.position = "none")

# original
d %>% 
  gather() %>% 
  mutate(x = rep(1:4, times = 5),
         possibility = rep(1:5, each = 4)) %>% 
  
  ggplot(aes(x = x, y = possibility, 
             fill = value %>% as.character())) +
  geom_point(shape = 21, size = 5) +
  scale_fill_manual(values = c("white", "navy")) +
  scale_x_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(.75, 4.25),
                  ylim = c(.75, 5.25)) +
  theme(legend.position = "none")

```
```{r}
tibble(draw = 1:3, marbles = 4) %>% 
  mutate(possibilities = marbles ^ draw)

(
  d <-
    tibble(position = c((1:4^1) / 4^0,
                        (1:4^2) / 4^1,
                        (1:4^3) / 4^2),
           draw = rep(1:3, times = c(4^1, 4^2, 4^3)),
           fill = rep(c("b", "w"), times = c(1, 3)) %>%
             rep(., times = c(4^0 + 4^1 + 4^2))
           
           
           )
)

d %>% 
  ggplot(aes(x = position, y = draw)) +
  geom_point(aes(fill = fill),
             shape = 21, size = 3) +
  scale_y_continuous(breaks = 1:3) +
  scale_fill_manual(values  = c("navy", "white")) +
  theme(panel.grid.minor = element_blank(),
        legend.position = "none")

```

```{r}
(
  lines_1 <-
  tibble(x    = rep((1:4), each = 4),
         xend = ((1:4^2) / 4),
         y    = 1,
         yend = 2)
  )

(
  lines_2 <-
  tibble(x    = rep(((1:4^2) / 4), each = 4),
         xend = (1:4^3)/(4^2),
         y    = 2,
         yend = 3)
  )
d %>% 
  ggplot(aes(x = position, y = draw)) +
  geom_segment(data  = lines_1,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size  = 1/3) +
  geom_segment(data  = lines_2,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size  = 1/3) +
  geom_point(aes(fill = fill),
             shape = 21, size = 3) +
  scale_y_continuous(breaks = 1:3) +
  scale_fill_manual(values  = c("navy", "white")) +
  theme(panel.grid.minor = element_blank(),
        legend.position = "none")
```

```{r}
d %>% 
  ggplot(aes(x = position, y = draw)) +
  geom_segment(data  = lines_1,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size  = 1/3) +
  geom_segment(data  = lines_2,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size  = 1/3) +
  geom_point(aes(fill = fill),
             shape = 21, size = 4) +
  scale_fill_manual(values  = c("navy", "white")) +
  scale_x_continuous(limits = c(0, 4), breaks = NULL) +
  scale_y_continuous(limits = c(0.75, 3), breaks = NULL) +
  theme(panel.grid = element_blank(),
        legend.position = "none") +
  coord_polar() +
  labs(x = NULL, y = NULL)
```


```{r}
(d <- tibble(toss = c("w", "l", "w", "w", "w", "l", "w", "l", "w")))

d <-
  d %>% 
  mutate(n_trials  = 1:9,
         n_success = cumsum(toss == "w"))

sequence_length <- 50

e <- 
  d %>% 
  expand(n_trials, 
         p_water = seq(from = 0, to = 1, length.out = sequence_length)) %>%
  left_join(d, by = "n_trials") %>%
  group_by(p_water) %>% 
  mutate(lagged_n_success = lag(n_success, k = 1),
         lagged_n_trials  = lag(n_trials,  k = 1)) %>% 
  ungroup() 
#%>% 
  mutate(prior = ifelse(n_trials == 1, .5,
                                     dbinom(x    = lagged_n_success, 
                                            size = lagged_n_trials, 
                                            prob = p_water)),
         strip = str_c("n = ", n_trials),
         likelihood = dbinom(x    = n_success, 
                             size = n_trials, 
                             prob = p_water),
         ) %>% 
  # the next three lines allow us to normalize the prior and the likelihood, putting them both in a probability metric 
  group_by(n_trials) %>% 
  mutate(prior      = prior      / sum(prior),
         likelihood = likelihood / sum(likelihood)) %>%   
  
  ggplot(aes(x = p_water)) +
  geom_line(aes(y = prior), linetype = 2) +
  geom_line(aes(y = likelihood)) +
  scale_x_continuous("proportion water", breaks = c(0, .5, 1)) +
  scale_y_continuous("plausibility", breaks = NULL) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~strip, scales = "free_y")
```

```{r}
tibble(prob = seq(from = 0, to = 1, by = .01)) %>%
  ggplot(aes(x = prob,
             y = dbinom(x = 6, size = 9, prob = prob))) +
  geom_line() +
  labs(x = "probability",
       y = "binomial likelihood") + 
  theme(panel.grid = element_blank())
```

```{r}
sequence_length <- 1e3

d <-
  tibble(probability = seq(from = 0, to = 1, length.out = sequence_length)) %>% 
  expand(probability, row = c("flat", "stepped", "Laplace")) %>% 
  arrange(row, probability) %>% 
  mutate(prior = ifelse(row == "flat", 1,
                        ifelse(row == "stepped", rep(0:1, each = sequence_length/2),
                               exp(-abs(probability - .5) / .25) / ( 2 * .25))),
         likelihood = dbinom(x = 6, size = 9, prob = probability)) %>% 
  group_by(row) %>% 
  mutate(posterior = prior * likelihood / sum(prior * likelihood)) %>% 
  gather(key, value, -probability, -row) %>% 
  ungroup() %>% 
  mutate(key = factor(key, levels = c("prior", "likelihood", "posterior")),
         row = factor(row, levels = c("flat", "stepped", "Laplace"))) 

d
```

```{r}
range(d$value)
```

```{r}
library(brms)
globe_qa_brms <-
  brm(data = list(w = 24), 
      family = binomial(link = "identity"),
      w | trials(36) ~ 1,
      prior = prior(normal(.5, 1), class = Intercept),
      control = list(adapt_delta = 0.9))
```

```{r}
globe_qa_brms
```

```{r}
a <- 
tibble(pr_positive_vampire   = .95,
       pr_positive_mortal    = .01,
       pr_vampire            = .001) %>% 
  mutate(pr_positive         = pr_positive_vampire * pr_vampire + pr_positive_mortal * (1 - pr_vampire)) %>% 
  mutate(pr_vampire_positive = pr_positive_vampire * pr_vampire / pr_positive) %>% 
  glimpse()
a
```


```{r}
glimpse(a)
```
```{r}
set.seed(1000)
(
pos <- replicate(100, runif(16, -1, 1)) %>%
    as_tibble() %>%
    rbind(1, .)
  
)

```


```{r}
rbind(2, pos)
```

