---
title: "R Notebook"
output:
  html_notebook: default
  pdf_document: default
---

```{r}
library(rethinking)
data(reedfrogs)
d <- reedfrogs
rm(reedforgs)
detach(package:rethinking, unload = T)
library(brms)
```

```{r}
library(tidyverse)
glimpse(d)
```

```{r}
d <- d %>%
  mutate(tank = 1:nrow(.))
d
```

```{r}
b12.1 <- 
  brm(data = d, family = binomial,
      surv | trials(density) ~ 0 + factor(tank),
      prior(normal(0, 5), class = b),
      iter = 2000, warmup = 500, chains = 4, cores = 4,
      seed = 12)
```

```{r}
summary(b12.1)
```

```{r}
b12.2 <- 
  brm(data = d, family = binomial,
      surv | trials(density) ~ 1 + (1 | tank),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(cauchy(0, 1), class = sd)),
      iter = 4000, warmup = 1000, chains = 4, cores = 4,
      seed = 12)
```

```{r}
b12.1 <- add_criterion(b12.1, "waic")
b12.2 <- add_criterion(b12.2, "waic")

w <- loo_compare(b12.1, b12.2, criterion = "waic")

print(w, simplify = F)
```


```{r}
cbind(waic_diff = w[, 1] * -2,
      se        = w[, 2] *  2)
```



```{r}
post <- posterior_samples(b12.2, add_chain = TRUE)
post
```

```{r}
post_mdn <-
  coef(b12.2, robust = TRUE)$tank[, , ] %>%
  as_tibble() %>%
  bind_cols(d) %>%
  mutate(post_mdn = inv_logit_scaled(Estimate))
post_mdn
```

```{r}
#install.packages("ggthemes", dependencies = T) 
library(ggthemes)
```



```{r}
p1 <- post_mdn %>%
  ggplot(aes(x = tank)) +
  geom_hline(
    yintercept = inv_logit_scaled(median(post$b_Intercept)),
    linetype = 2, size = 1 / 4
  ) +
  geom_vline(xintercept = c(16.5, 32.5), size = 1/4) +
  geom_point(aes(y = propsurv), color = "orange2") +
  geom_point(aes(y = post_mdn), shape = 1) +
  coord_cartesian(ylim = c(0, 1)) +
  scale_x_continuous(breaks = c(1, 16, 32, 48)) +
  labs(
    title = "Multilevel shrinkage!",
    subtitle = "The empirical proportions are in orange while the model-implied \nproportions are the black cirles.\nThe dashed line is the model-implied average survival proportion."
  ) +
  annotate("text", x = c( 8, 16 + 8, 32 +8), y = 0,
           label = c("small tanks", "medium tanks", "large tanks")) +
  theme_fivethirtyeight() +
  theme(panel.grid = element_blank())
p1
```



```{r}
# before
tibble(x = c(-4, 5)) %>%
  ggplot(aes(x = x)) +
  mapply(
    function(mean, sd) {
      stat_function(fun = dnorm,
                    args = list(mean = mean, sd = sd),
                    alpha = .2,
                    color = "orange2")
    }, 
    mean = post[1:100, 1],
    sd = post[1:100, 2] 
  ) +
  labs(
    title = "Population survival distribution",
    subtitle = "The Gaussians are on the log-odds scale."
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(-3, 4)) +
  theme_fivethirtyeight() +
  theme(
    plot.title = element_text(size = 13),
    plot.subtitle = element_text(size = 10)
  )
```

```{r}
# after
set.seed(12)

post %>%
  sample_n(30, replace = FALSE) %>%
  expand(nesting(iter, b_Intercept, sd_tank__Intercept),
    x = seq(-4, 5, length.out = 100)
  ) %>%
  mutate(
    y = dnorm(x, b_Intercept, sd_tank__Intercept)
  ) %>%
  ggplot(aes(x = x, y = y, group = iter)) +
  geom_line(alpha = .5, color = "orange2") +
  labs(
    title = "Population survival distribution",
    subtitle = "The Gaussians are on the log-odds scale."
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(-3, 4)) +
  theme_fivethirtyeight() +
  theme(
    plot.title = element_text(size = 13),
    plot.subtitle = element_text(size = 10)
  )
```



```{r}
post %>%
  transmute(
    prob = inv_logit_scaled(
      rnorm(nrow(.), mean = b_Intercept, sd = sd_tank__Intercept)
    )
  ) %>%
  ggplot(aes(prob)) +
  geom_density(size = 0, fill = "orange2") +
  scale_y_continuous(NULL, breaks = NULL) +
  ggtitle("Probability of survival") +
  theme_fivethirtyeight()
```



```{r}
b12.2.e <- 
  update(
    b12.2,
    prior = c(
      prior(normal(0, 1), class = Intercept),
      prior(exponential(1), class = sd)
    )
  )
```


```{r}
summary(b12.2.e)
```






```{r}
print(b12.2.e)
```

```{r}
tibble(x = seq(from = 0, to = 6, by = .01)) %>%
  ggplot(aes(x = x)) +
  geom_ribbon(
    aes(ymin = 0, ymax = dexp(x, rate = 1)),
    fill = "orange2", alpha = 1 / 3
  ) +
  geom_density(
    data = posterior_samples(b12.2.e),
    aes(x = sd_tank__Intercept),
    fill = "orange2", size = 0
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  coord_cartesian(xlim = c(0, 5)) +
  labs(
    title = "Bonus prior/posterior plot for sd_tank__Intercept",
    subtitle = "The prior is the semitransparent ramp in the background. \nThe posterior is the solid orange mound."
  )
```



```{r}
set.seed(1223)
(
  dsim <-
  dsim %>%
  mutate(si = rbinom(n = n(), prob = inv_logit_scaled(true_a), size = ni))
  )
```



# 12.1

```{r}
library(rethinking)
data(reedfrogs)
d <- reedfrogs
rm(reedfrogs)
detach(pacakge:rethinking, unload = T)
library(brms)
```


















