---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
set.seed(4)
pos <-
  replicate(100, runif(16, -1, 1)) %>%
  as_tibble() %>%
  rbind(0, .) %>%
  mutate(step = 0:16) %>%
  gather(key, value, -step) %>%
  mutate(person = rep(1:100, each = 17)) %>%
  group_by(person) %>%
  mutate(position = cumsum(value)) %>%
  ungroup()
```

```{r}
glimpse(pos)
```

```{r}
ggplot(data = pos, aes(x = step, y = position, group = person)) +
  geom_vline(xintercept = c(4, 8, 16), linetype = 2) +
  geom_line(aes(color = person < 2, alpha = person < 2)) +
  scale_color_manual(values = c("skyblue4", "black")) +
  scale_alpha_manual(values = c(1/5, 1)) +
  scale_x_continuous("step number", breaks = c(0, 4, 8, 12, 16)) + 
  theme(legend.position = "none")
```

```{r}
# Figure 4.2.a.
pos %>%
  filter(step == 4) %>%
  ggplot(aes(x = position)) +
  geom_line(stat = "density", color = "dodgerblue1") +
  coord_cartesian(xlim = -6:6) +
  labs(title = "4 steps")

# Figure 4.2.b.
pos %>%
  filter(step == 8) %>%
  ggplot(aes(x = position)) +
  geom_density(color = "dodgerblue2") +
  coord_cartesian(xlim = -6:6) +
  labs(title = "8 steps")

# Figure 4.2.c.
pos %>%
  filter(step == 16) %>%
  ggplot(aes(x = position)) +
  stat_function(fun = dnorm, 
                args = list(mean = 0, sd = 2.180408),
                linetype = 2) +  # 2.180408 came from the previous code block
  geom_density(color = "transparent", fill = "dodgerblue3", alpha = 1/2) +
  coord_cartesian(xlim = -6:6) +
  labs(title = "16 steps",
       y     = "density")
```


```{r}
set.seed(4)
prod(1 + runif(12, 0, 0.1))
```

```{r}
set.seed(4)
growth <- tibble(growth = map_dbl(1:10000, ~ prod(1 + runif(12, 0, 0.1))))
growth

ggplot(data = growth, aes(x = growth)) +
  geom_density()
```


```{r}

set.seed(4)

samples <-
  tibble(big   = map_dbl(1:10000, ~ prod(1 + runif(12, 0, 0.5))),
         small = map_dbl(1:10000, ~ prod(1 + runif(12, 0, 0.01)))) %>% 
  # wrangle
  gather(distribution, samples) 

# plot
samples %>% 
  ggplot(aes(x = samples)) +
  geom_density(fill = "black",) +
  facet_wrap(~distribution, scales = "free") 
```


```{r}
library(rethinking)
data(Howell1)
d <- Howell1
rm(Howell1)
detach(package:rethinking, unload = T)
library(brms)
```

```{r}
str(d)
```

```{r}
d %>% 
  select(height) %>%
  head()
```


```{r}
d2 <- d %>%
  filter(age >= 18)
```

```{r}
d2
```


```{r}
tibble(x = seq(from = 100, to = 250, by = .1)) %>%
  mutate(y = dnorm(x, mean = 178, sd = 20)) %>%
  ggplot(aes(x, y)) +
  geom_line() +
  ylab("density")
```


```{r}
tibble(x = seq(-10, 60, by = .1)) %>%
  mutate(y = dunif(x, min = 0, max = 50)) %>%
  ggplot(aes(x, y)) +
  geom_line() +
  scale_y_continuous(NULL, breaks = NULL) +
  theme(panel.grid = element_blank())
```


```{r}
n <- 1e4
set.seed(4)
tibble(
  sample_mu = rnorm(n, mean = 178, sd = 20),
  sample_sigma = runif(n, min = 0, max = 50)
) %>%
  mutate(
    x = rnorm(n, mean = sample_mu, sd = sample_sigma)
  ) %>%
  ggplot(aes(x)) + 
  geom_density(fill = "black", size = 0) +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(
    subtitle = expression(paste("Prior predictive distirubtion for ", italic(h[i]))),
    x = NULL
  )


```


```{r}
n <- 200

d_grid <- 
  tibble(
    mu = seq(140, 160, length.out = n),
    sigma = seq(4, 9, length.out = n)
  ) %>% expand(mu, sigma)

head(d_grid)
```

```{r}
grid_function <- function(mu, sigma) {
  dnorm(d2$height, mean = mu, sd = sigma, log = T) %>%
    sum()
}
```

```{r}
grid_function(140, 4)
```




```{r}
d_grid <-
  d_grid %>%
  mutate(log_likelihood = map2_dbl(mu, sigma, grid_function)) %>%
  mutate(
    prior_mu = dnorm(mu, mean = 178, sd = 20, log = T),
    prior_sigma = dunif(sigma, min = 0, max = 50, log = T),
    product = log_likelihood + prior_mu + prior_sigma,
    probability = exp(product - max(product))
  ) %>%
  arrange(desc(probability))
d_grid
```

```{r}
d_grid %>%
  ggplot(aes(x = mu, y = sigma, z = probability)) +
  geom_contour() +
  coord_cartesian(
    xlim = range(d_grid$mu),
    ylim = range(d_grid$sigma)
  ) +
  labs(
    x = expression(mu),
    y = expression(sigma)
  ) +
  theme(panel.grid = element_blank())
```

```{r}
d_grid %>%
  ggplot(aes(x = mu, y = sigma)) +
  geom_raster(aes(fill = probability), interpolate = TRUE) +
  scale_fill_viridis_c(option = "A") +
  labs(
    x = expression(mu),
    y = expression(sigma)
  ) +
  theme(panel.grid = element_blank())
```


```{r}
set.seed(4)
d_grid_samples <- d_grid %>%
  sample_n(1e4, replace = TRUE, weight = probability) 

d_grid_samples %>%
  ggplot(aes(mu, sigma)) +
  geom_point(size = .9, alpha = 1/15) +
  labs(
    x = expression(mu[samples]),
    y = expression(simga[samples])
  ) + 
  theme(panel.grid = element_blank())
```

```{r}
d_grid_samples %>%
  select(mu, sigma) %>%
  gather() %>%
  ggplot(aes(value)) +
  geom_density(fill = "grey33", size = 0) + 
  facet_wrap(~key, scales = "free")  +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  theme(panel.grid = element_blank())
```


```{r}
library(tidybayes)

d_grid_samples %>%
  select(mu, sigma) %>%
  gather() %>%
  group_by(key) %>%
  median_qi(value)
```

```{r}
set.seed(4)
d3 <- sample(d2$height, size = 20)
d3
```

```{r}
n <- 200
d_grid <-
  tibble(mu = seq(150, 170, length.out = n),
         sigma = seq(4, 20, length.out = n)) %>%
  expand(mu, sigma)
d_grid
```

```{r}
grid_function <- function(mu, sigma) {
  dnorm(d3, mean = mu, sd = sigma, log = T) %>%
    sum()
}
```

```{r}
d_grid <-
  d_grid %>% 
  mutate(log_likelihood = map2_dbl(mu, sigma, grid_function)) %>% 
  mutate(prior_mu       = dnorm(mu,    mean = 178, sd  = 20, log = T),
         prior_sigma    = dunif(sigma, min  = 0,   max = 50, log = T)) %>% 
  mutate(product        = log_likelihood + prior_mu + prior_sigma) %>% 
  mutate(probability    = exp(product - max(product)))
d_grid
```


```{r}
set.seed(4)
d_grid_samples <- 
  d_grid %>% 
  sample_n(size = 1e4, replace = T, weight = probability)

d_grid_samples %>% 
  ggplot(aes(x = mu, y = sigma)) + 
  geom_point(size = .9, alpha = 1/15) +
  scale_fill_viridis_c() +
  labs(x = expression(mu[samples]),
       y = expression(sigma[samples])) +
  theme(panel.grid = element_blank())
```

```{r}
d_grid_samples %>% 
  select(mu, sigma) %>% 
  gather() %>% 

  ggplot(aes(x = value)) + 
  geom_density(fill = "grey33", size = 0) +
  scale_y_continuous(NULL, breaks = NULL) +
  xlab(NULL) +
  theme(panel.grid = element_blank()) +
  facet_wrap(~key, scales= "free")
```


```{r}
b4.1 <-
  brm(
    height ~ 1,
    data = d2, family = gaussian,
    prior = c(
      prior(normal(178, 20), class = Intercept),
      prior(uniform(0, 50), class = sigma)
    ),
    iter = 31000, warmup = 30000, chains = 4, cores = 4,
    seed = 4
  )
```

```{r}
b4.1_half_cauchy <-
  brm(
    height ~ 1,
    data = d2, family = gaussian,
    prior = c(
      prior(normal(178, 20), class = Intercept),
      prior(cauchy(0, 1), class = sigma)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    seed = 4
  )
```


```{r}
plot(b4.1)
```


```{r}
plot(b4.1_half_cauchy)
```

```{r}
launch_shinystan(b4.1)
```

```{r}
summary(b4.1_half_cauchy, prob = .89)
```


```{r}
broom::tidy(b4.1_half_cauchy)
```

```{r}
b4.2 <- 
  brm(data = d2, family = gaussian,
      height ~ 1,
      prior = c(prior(normal(178, .1), class = Intercept),
                prior(uniform(0, 50), class = sigma)),
      iter = 3000, warmup = 2000, chains = 4, cores = 4,
      seed = 4)
```


```{r}
summary(b4.2)
```

```{r}
post <- posterior_samples(b4.1_half_cauchy)
post
```


```{r}
post %>%
  select(-lp__) %>%
  cor()
```

```{r}
summary(post[, 1:2])
```

```{r}
t(apply(post[, 1:2], 2, quantile, probs = c(.5, .025, .75)))
```

```{r}
post %>%
  select(-lp__) %>%
  gather(parameter) %>%
  group_by(parameter) %>%
  summarise(
    mean = mean(value),
    sd = sd(value),
    `2.5_percentile` = quantile(value, probs = .025),
    `97.5_percentile` = quantile(value, probs = 0.975)
  ) %>%
  mutate_if(is.numeric, round, digits = 2)
```

```{r}
posterior_summary(b4.1_half_cauchy)
```

```{r}
post %>%
  select(-lp__) %>%
  gather(parameter) %>%
  group_by(parameter) %>%
  mean_qi(value) %>%
  mutate_if(is.numeric, round, digits = 2)
```

```{r}
b4.3 <-
  brm(
    height ~ 1 + weight,
    data = d2, family = gaussian,
    prior = c(
      prior(normal(156, 100), class = Intercept),
      prior(normal(0, 10), class = b),
      prior(cauchy(0, 50), class = sigma)
    ),
    iter = 41000, warmup = 40000, chains = 4, cores = 4,
    seed = 4
  )
```


```{r}
plot(b4.3)
```

```{r}
posterior_summary(b4.3)[1:3, ]
```

```{r}
posterior_samples(b4.3) %>%
  select(-lp__) %>%
  cor() %>%
  round(digits = 2)
```

```{r}
d2 <- d2 %>%
  mutate(weight_c = weight - mean(weight))
```

```{r}
b4.4 <- 
  brm(data = d2, family = gaussian,
      height ~ 1 + weight_c,
      prior = c(prior(normal(178, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(uniform(0, 50), class = sigma)),
      iter = 46000, warmup = 45000, chains = 4, cores = 4,
      seed = 4)
```





```{r}
pairs(b4.4)
```




```{r}
fixef(b4.3)
```

```{r}
d2 %>%
  ggplot(aes(weight, height)) + 
  geom_abline(intercept = fixef(b4.3)[1], slope = fixef(b4.3)[2]) +
  geom_point(shape = 1, size = 2, color = "royalblue") +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
post <- posterior_samples(b4.3)
post %>%
  slice(1:5)
```

```{r}
n <- 10

b.10 <- 
  brm(data = d2 %>%
        slice(1:n),  # note our tricky use of `n` and `slice()`
      family = gaussian,
      height ~ 1 + weight,
      prior = c(prior(normal(178, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(cauchy(0, 1), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 4)

n <- 50

b.50 <- 
  brm(data = d2 %>%
        slice(1:n), 
      family = gaussian,
      height ~ 1 + weight,
      prior = c(prior(normal(178, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(cauchy(0, 1), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 4)

n <- 150

b.150 <- 
  brm(data = d2 %>%
        slice(1:n), 
      family = gaussian,
      height ~ 1 + weight,
      prior = c(prior(normal(178, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(cauchy(0, 1), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 4)

n <- 352

b.352 <- 
  brm(data = d2 %>%
        slice(1:n), 
      family = gaussian,
      height ~ 1 + weight,
      prior = c(prior(normal(178, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(cauchy(0, 1), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      seed = 4)
```



```{r}
plot(b.10)
print(b.10)

plot(b.50)
print(b.50)

plot(b.150)
print(b.150)

plot(b.352)
print(b.352)
```

```{r}
post10  <- posterior_samples(b.10)
post50  <- posterior_samples(b.50)
post150 <- posterior_samples(b.150)
post352 <- posterior_samples(b.352)
```

```{r}
p10 <- 
  ggplot(data =  d2[1:10 , ], 
         aes(x = weight, y = height)) +
  geom_abline(intercept = post10[1:20, 1], 
              slope     = post10[1:20, 2],
              size = 1/3, alpha = .3) +
  geom_point(shape = 1, size = 2, color = "royalblue") +
  coord_cartesian(xlim = range(d2$weight),
                  ylim = range(d2$height)) +
  labs(subtitle = "N = 10") +
  theme_bw() +
  theme(panel.grid = element_blank())

p50 <-
  ggplot(data =  d2[1:50 , ], 
         aes(x = weight, y = height)) +
  geom_abline(intercept = post50[1:20, 1], 
              slope     = post50[1:20, 2],
              size = 1/3, alpha = .3) +
  geom_point(shape = 1, size = 2, color = "royalblue") +
  coord_cartesian(xlim = range(d2$weight),
                  ylim = range(d2$height)) +
  labs(subtitle = "N = 50") +
  theme_bw() +
  theme(panel.grid = element_blank())

p150 <-
  ggplot(data =  d2[1:150 , ], 
         aes(x = weight, y = height)) +
  geom_abline(intercept = post150[1:20, 1], 
              slope     = post150[1:20, 2],
              size = 1/3, alpha = .3) +
  geom_point(shape = 1, size = 2, color = "royalblue") +
  coord_cartesian(xlim = range(d2$weight),
                  ylim = range(d2$height)) +
  labs(subtitle = "N = 150") +
  theme_bw() +
  theme(panel.grid = element_blank())

p352 <- 
  ggplot(data =  d2[1:352 , ], 
         aes(x = weight, y = height)) +
  geom_abline(intercept = post352[1:20, 1], 
              slope     = post352[1:20, 2],
              size = 1/3, alpha = .3) +
  geom_point(shape = 1, size = 2, color = "royalblue") +
  coord_cartesian(xlim = range(d2$weight),
                  ylim = range(d2$height)) +
  labs(subtitle = "N = 352") +
  theme_bw() +
  theme(panel.grid = element_blank())
```

```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
multiplot(p10, p150, p50, p352, cols = 2)
```

```{r}
mu_at_50 <-
  post %>%
  transmute(mu_at_50 = b_Intercept + b_weight * 50)
mu_at_50
```


```{r}
mu_at_50 %>%
  ggplot(aes(mu_at_50)) +
  geom_density(size = 0, fill = "royalblue") +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(x = expression(mu["height | weight = 50"])) +
  theme_classic()
```

```{r}
mean_hdi(mu_at_50[, 1], .width = c(.89, .95))
```

```{r}
mu_at_50 %>%
  ggplot(aes(mu_at_50)) +
  geom_density(size = 0, fill = "royalblue") +
  stat_pointintervalh(
    aes(y = 0), 
    point_interval = mode_hdi, .width = .95
  ) +
  scale_y_continuous(NULL, breaks = NULL) +
  labs(x = expression(mu["height | weight = 50"])) +
  theme_classic()
```

```{r}
mu <- fitted(b4.3, summary = F)
mu
```


```{r}
weight_seq <- tibble(weight = seq(from = 25, to = 70, by = 1))

mu <-
  fitted(b4.3,
         summary = F,
         newdata = weight_seq) %>%
  as_tibble() %>%
  # here we name the columns after the `weight` values from which they were computed
  set_names(25:70) %>% 
  mutate(iter = 1:n())

str(mu)
```


```{r}
mu <- 
  mu %>%
  gather(weight, height, -iter) %>% 
  # We might reformat `weight` to numerals
  mutate(weight = as.numeric(weight))

head(mu)
```

```{r}
d2 %>%
  ggplot(aes(x = weight, y = height)) +
  geom_point(data = mu %>% filter(iter < 101),
             alpha = .1)
```


```{r}
mu_summary <-
  fitted(b4.3, 
         newdata = weight_seq) %>%
  as_tibble() %>%
  # let's tack on the `weight` values from `weight_seq`
  bind_cols(weight_seq)

head(mu_summary)
```


```{r}
d2 %>%
  ggplot(aes(x = weight, y = height)) +
  geom_smooth(data = mu_summary,
              aes(y = Estimate, ymin = Q2.5, ymax = Q97.5),
              stat = "identity",
              fill = "grey70", color = "black", alpha = 1, size = 1/2) +
  geom_point(color = "navyblue", shape = 1, size = 1.5, alpha = 2/3) +
  coord_cartesian(xlim = range(d2$weight)) +
  theme(text = element_text(family = "Times"),
        panel.grid = element_blank())
```

```{r}
weight_seq <- tibble(weight = seq(from = 25, to = 70, by = .01))
pred_height <-
  predict(b4.3,
          newdata = weight_seq) %>%
  as_tibble() %>%
  bind_cols(weight_seq)
  
pred_height %>%
  slice(1:6)
d2 %>%
  ggplot(aes(x = weight)) +
  geom_ribbon(data = pred_height, 
              aes(ymin = Q2.5, ymax = Q97.5),
              fill = "grey83") +
  geom_smooth(data = mu_summary,
              aes(y = Estimate, ymin = Q2.5, ymax = Q97.5),
              stat = "identity",
              fill = "grey70", color = "black", alpha = 1, size = 1/2) +
  geom_point(aes(y = height),
             color = "navyblue", shape = 1, size = 1.5, alpha = 2/3) +
  coord_cartesian(xlim = range(d2$weight),
                  ylim = range(d2$height)) +
  theme(text = element_text(family = "Times"),
        panel.grid = element_blank())
```


















































<!-- ------------------------------------------------------ -->
<!-- old verseion 5/21 -->


<!-- ```{r} -->
<!-- set.seed(1000) -->
<!-- pos <- -->
<!--   replicate(100, runif(16, -1, 1)) %>% -->
<!--   as_tibble() %>% -->
<!--   rbind(0, .) %>% -->
<!--   mutate(step = 0:16) %>% -->
<!--   gather(key, value, -step) %>% -->
<!--   mutate(person = rep(1:100, each = 17)) %>% -->
<!--   group_by(person) %>% -->
<!--   mutate(position = cumsum(value)) %>% -->
<!--   ungroup() -->
<!-- pos -->
<!-- ``` -->

<!-- ```{r} -->
<!-- glimpse(pos) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot( -->
<!--   data = pos, -->
<!--   aes(x = step, y = position, group = person)) + -->
<!--   geom_vline(xintercept = c(4, 8, 16), linetype = 2) + -->
<!--   geom_line(aes(color = person < 2, alpha = person < 2)) + -->
<!--   scale_color_manual(values = c("skyblue4", "black")) + -->
<!--   scale_alpha_manual(values = c(1/5, 1)) + -->
<!--   scale_x_continuous("step number", breaks = c(0, 4, 12, 16)) + -->
<!--   theme(legend.position = "none") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pos %>% -->
<!--   filter(step == 16) %>% -->
<!--   ggplot(aes(position)) + -->
<!--   geom_line(stat = "density", color = "dodgerblue1") + -->
<!--   coord_cartesian(xlim = -6:6) + -->
<!--   labs(title = "4 steps") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pos %>% -->
<!--   filter(step %in% c(4, 8)) %>% -->
<!--   ggplot(aes(position)) + -->
<!--   geom_density(color = "dodgerblue1") + -->
<!--   coord_cartesian(xlim = -6:6) + -->
<!--   facet_wrap(~ step) + -->
<!--   labs(title = "steps") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pos %>% -->
<!--   filter(step == 16) %>% -->
<!--   summarise( -->
<!--     mean = mean(position), -->
<!--     sd = sd(position) -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Figure 4.2.c. -->
<!-- pos %>% -->
<!--   filter(step == 16) %>% -->
<!--   ggplot(aes(position)) + -->
<!--   geom_line( -->
<!--     data = tibble(position = seq(-7, 7, by = .1)), -->
<!--     aes(x = position, y = dnorm(position, 0, 2.381768)), -->
<!--     linetype = 2 -->
<!--   ) + -->
<!--   geom_density( -->
<!--     color = "transparent", -->
<!--     fill = "dodgerblue3", -->
<!--     alpha = 1/2 -->
<!--   ) + -->
<!--   coord_cartesian(xlim = -6:6) +  -->
<!--   labs( -->
<!--     title = "16 steps", -->
<!--     y = "density" -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(1) -->
<!-- prod(1 + runif(12, 0, 0.1)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(1) -->
<!-- tibble(a = 1, b = runif(12, 0, 0.1)) %>% -->
<!--   mutate(c = a + b) %>% -->
<!--   summarise(p = prod(c)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(.1) -->
<!-- growth <- -->
<!--   replicate(10000, prod(1 + runif(12, 0, 0.1))) %>% -->
<!--   as_tibble() -->
<!-- growth -->

<!-- ggplot(data = growth, aes(x = value)) +  -->
<!--   geom_density() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(412) -->
<!-- big <- replicate(10000, prod(1 + runif(12, 0, 0.5))) -->

<!-- set.seed(412) -->
<!-- small <- replicate(10000, prod(1 + runif(12, 0, 0.01))) -->

<!-- tibble( -->
<!--   samples = c(big, small), -->
<!--   distribution = rep(c("big", "small"), each = 10000) -->
<!-- ) %>% -->
<!-- ggplot(aes(x = samples)) + -->
<!--   geom_density(fill = "black", color = "transparent") + -->
<!--   facet_wrap(~ distribution, scales = "free") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(12) -->
<!-- replicate(10000, log(prod(1 + runif(12, 0, 0.5)))) %>% -->
<!--   as_tibble() %>% -->
<!--   ggplot(aes(value)) +  -->
<!--   geom_density(color = "transparent", fill = "gray33") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- n_points <- 100 -->
<!-- d <- -->
<!--   tibble( -->
<!--     w = 6, -->
<!--     n = 9, -->
<!--     p_grid = seq(0, 1, length.out = n_points)) %>% -->
<!--   mutate( -->
<!--     prior = dunif(p_grid, 0, 1), -->
<!--     likelihood = dbinom(w, n, p_grid) -->
<!--   ) %>% -->
<!--   mutate(posterior = likelihood * prior) %>% -->
<!--   mutate(posterior = posterior / sum(posterior)) -->
<!-- d -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d %>% -->
<!--   select(-w, -n) %>% -->
<!--   gather(key, value, -p_grid) %>% -->
<!--   mutate(key = factor(key, levels = c("prior", "likelihood", "posterior"))) %>% -->
<!--   ggplot(aes(x = p_grid, ymin = 0, ymax = value, fill = key)) + -->
<!--   geom_ribbon() + -->
<!--   facet_wrap(~ key, scales = "free") + -->
<!--   scale_fill_manual(values = c("blue", "red", "purple")) + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   theme(legend.position = "none") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ?dunif -->
<!-- ``` -->

<!-- ```{r} -->
<!-- install.packages(c("coda","mvtnorm","devtools","loo")) -->
<!-- library(devtools) -->
<!-- devtools::install_github("rmcelreath/rethinking") -->
<!-- library(rethinking) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- data(Howell1) -->
<!-- d <- Howell1 -->
<!-- d -->
<!-- rm(Howell1) -->
<!-- detach(package:rethinking, unload = TRUE) -->
<!-- library(brms) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- glimpse(d) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- d %>% -->
<!--   select(height) %>% head() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 <- -->
<!--   d %>% -->
<!--   filter(age >= 18) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- tibble( -->
<!--   x = seq(100, 250, by = .1) -->
<!-- ) %>%  -->
<!--   ggplot(aes(x = x, y = dnorm(x, mean = 178, sd = 20))) + -->
<!--   geom_line() + -->
<!--   ylab("density") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- tibble( -->
<!--   x = seq(-10, 60, by = .1) -->
<!-- ) %>% -->
<!--   ggplot(aes(x = x, y = dunif(x, min = 0, max = 50))) + -->
<!--   geom_line() + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- n <- 1e4 -->
<!-- set.seed(432) -->
<!-- tibble( -->
<!--   sample_mu = rnorm(n, mean = 178, sd = 20), -->
<!--   sample_sigma = runif(n, min = 0, max = 50) -->
<!-- ) %>% -->
<!--   mutate(x = rnorm(n, mean = sample_mu, sd = sample_sigma)) -> df -->

<!-- df %>% -->
<!--   ggplot(aes(x = x)) + -->
<!--   geom_density(fill = "black", size = 0) + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   labs( -->
<!--     subtitle = expression(paste("Prior predictive distribution for ", italic(h[i]))), -->
<!--     x = NULL  -->
<!--   ) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- df -->
<!-- ``` -->

<!-- ```{r} -->
<!-- n <- 200 -->
<!-- d_grid <- -->
<!--   tibble( -->
<!--     mu = seq(140, 160, length.out = n), -->
<!--     sigma = seq(4, 9, length.out = n) -->
<!--   ) %>% -->
<!--   expand(mu, sigma) -->
<!-- d_grid -->
<!-- ``` -->

<!-- ```{r} -->
<!-- grid_function <- function(mu, sigma) { -->
<!--   dnorm(d2$height, mean = mu, sd = sigma, log = TRUE) %>% -->
<!--     sum() -->
<!-- } -->
<!-- ``` -->


<!-- ```{r} -->
<!-- d_grid <-  -->
<!--   d_grid %>% -->
<!--   mutate(log_likelihood = map2(mu, sigma, grid_function)) %>% -->
<!--   unnest() %>% -->
<!--   mutate( -->
<!--     prior_mu = dnorm(mu, mean = 178, sd = 20, log = T), -->
<!--     prior_sigma = dunif(sigma, min = 0, max = 50, log = T) -->
<!--   ) %>% -->
<!--   mutate( -->
<!--     product = log_likelihood + prior_mu + prior_sigma -->
<!--   ) %>% -->
<!--   mutate(probability = exp(product - max(product))) -->

<!-- head(d_grid) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d_grid %>% -->
<!--   ggplot(aes(x = mu, y = sigma, z = probability)) + -->
<!--   geom_contour() + -->
<!--   labs( -->
<!--     x = expression(mu), -->
<!--     y = expression(sigma) -->
<!--   ) + -->
<!--   coord_cartesian( -->
<!--     xlim = range(d_grid$mu), -->
<!--     ylim = range(d_grid$sigma) -->
<!--   ) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d_grid %>% -->
<!--   ggplot(aes(x = mu, y = sigma)) + -->
<!--   geom_raster(aes(fill = probability)) + -->
<!--   scale_fill_viridis_c() + -->
<!--   labs( -->
<!--     x = expression(mu), -->
<!--     y = expression(sigma) -->
<!--   ) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(434) -->
<!-- d_grid_samples <- -->
<!--   d_grid %>% -->
<!--     sample_n(size = 1e4, replace = T, weight = probability) -->

<!-- d_grid_samples %>% -->
<!--   ggplot(aes(x = mu, y = sigma)) + -->
<!--   geom_point(size = .9, alpha = 1 / 15) + -->
<!--   labs( -->
<!--     x = expression(mu[samples]), -->
<!--     y = expression(sigam[samples]) -->
<!--   ) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d_grid_samples %>% -->
<!--   select(mu, sigma) %>% -->
<!--   gather() %>% -->
<!--   ggplot(aes(x = value)) + -->
<!--   geom_density(fill = "grey33", size = 0) + -->
<!--   facet_wrap(~ key, scales = "free") + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   xlab(NULL) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library(tidybayes) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d_grid_samples %>% -->
<!--   select(mu, sigma) %>% -->
<!--   gather() %>% -->
<!--   group_by(key) %>% -->
<!--   median_qi(value, .width = .5) -->
<!--   #mode_hdi(value) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(4341) -->
<!-- (d3 <- sample(d2$height, size = 20)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- n <- 200 -->
<!-- d_grid <- -->
<!--   tibble( -->
<!--     mu = seq(150, 170, length.out = n), -->
<!--     sigma = seq(4, 20, length.out = n) -->
<!--   ) %>% -->
<!--   expand(mu, sigma) -->
<!-- d_grid -->
<!-- ``` -->


<!-- ```{r} -->
<!-- grid_function <- function(mu, sigma) { -->
<!--   dnorm(d3, mean = mu, sd = sigma, log = T) %>% -->
<!--   sum() -->
<!-- } -->
<!-- ``` -->


<!-- ```{r} -->
<!-- d_grid <- -->
<!--   d_grid %>% -->
<!--   mutate(log_likelihood = map2(mu, sigma, grid_function)) %>% -->
<!--   unnest() %>% -->
<!--   mutate( -->
<!--     prior_mu = dnorm(mu, mean = 178, sd = 20, log = T), -->
<!--     prior_sigma = dunif(sigma, min = 0, max = 50, log = T)  -->
<!--   ) %>% -->
<!--   mutate( -->
<!--     product = log_likelihood + prior_mu + prior_sigma -->
<!--   ) %>% -->
<!--   mutate(probability = exp(product - max(product))) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(4341) -->
<!-- d_grid_samples <- -->
<!--   d_grid %>% -->
<!--   sample_n(size = 1e4, replace = T, weight = probability) -->

<!-- d_grid_samples %>% -->
<!--   ggplot(aes(x = mu, y = sigma)) + -->
<!--   geom_point(size = .9, alpha = 1 / 15) + -->
<!--   scale_fill_viridis_c() + -->
<!--   labs( -->
<!--     x = expression(mu[samples]), -->
<!--     y = expression(sigma[samples]) -->
<!--   ) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.1 <- -->
<!--   brm( -->
<!--     height ~ 1, -->
<!--     data = d2,  -->
<!--     family = gaussian, -->
<!--     prior = c( -->
<!--       prior(normal(178, 20), class = Intercept), -->
<!--       prior(uniform(0, 50), class = sigma) -->
<!--     ), -->
<!--     iter = 31000, warmup = 30000, chains = 4, cores = 4 -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.1_half_cauchy <- -->
<!--   brm( -->
<!--     height ~ 1, -->
<!--     data = d2,  -->
<!--     family = gaussian, -->
<!--     prior = c( -->
<!--       prior(normal(178, 20), class = Intercept), -->
<!--       prior(cauchy(0, 1), class = sigma) -->
<!--     ), -->
<!--     iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b4.1_half_cauchy) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- summary(b4.1_half_cauchy) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.1_half_cauchy$fit -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.2 <- -->
<!--   brm( -->
<!--     height ~ 1, -->
<!--     data =d2, -->
<!--     family = gaussian, -->
<!--     prior = c( -->
<!--       prior(normal(178, .1), class = Intercept), -->
<!--       prior(uniform(0, 50), class = sigma) -->
<!--     ), -->
<!--     iter = 3000, warmup = 2000, chains = 4, cores = 4 -->
<!--   ) -->

<!-- plot(b4.2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post <- posterior_samples(b4.1_half_cauchy) -->
<!-- post %>% -->
<!--   select(b_Intercept, sigma) %>% -->
<!--   cor() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post[, 1:2] %>% -->
<!--   cov() %>% -->
<!--   diag() -->
<!-- ``` -->


<!-- ```{r} -->
<!-- summary(post[, 1:2]) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post %>% -->
<!--   select(-lp__) %>% -->
<!--   gather(parameter) %>% -->
<!--   group_by(parameter) %>% -->
<!--   summarise( -->
<!--     mean = mean(value), -->
<!--     sd = sd(value), -->
<!--     `2.5_percentile` = quantile(value, probs = .025), -->
<!--     `97.5_percentile` = quantile(value, probs = .975) -->
<!--   ) %>% -->
<!--   mutate_if(is.numeric, round, digits = 2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- posterior_summary(b4.1_half_cauchy) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post %>% -->
<!--   select(-lp__) %>% -->
<!--   gather(parameter) %>% -->
<!--   group_by(parameter) %>% -->
<!--   mean_qi(value) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot( -->
<!--   data = post, -->
<!--   aes(x = sigma) -->
<!-- ) + -->
<!--   geom_density(size = 1 / 10, fill = "black") + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   xlab(expression(sigma)) + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot( -->
<!--   data = d2, -->
<!--   aes(x = weight, y = height) -->
<!-- ) + -->
<!--   geom_point(shape = 1, size = 2) + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.3 <- -->
<!--   brm( -->
<!--     data = d2,  -->
<!--     family = gaussian, -->
<!--     height ~ 1 + weight, -->
<!--     prior = c( -->
<!--       prior(normal(156, 100), class = Intercept), -->
<!--       prior(normal(0, 10), class = b), -->
<!--       prior(uniform(0, 50), class = sigma) -->
<!--     ),  -->
<!--     iter = 41000, warmup = 40000, chains = 4, cores = 4 -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.3_half_cauchy <- -->
<!--   brm( -->
<!--     data = d2,  -->
<!--     family = gaussian, -->
<!--     height ~ 1 + weight, -->
<!--     prior = c( -->
<!--       prior(normal(156, 100), class = Intercept), -->
<!--       prior(normal(0, 10), class = b), -->
<!--       prior(cauchy(0, 1), class = sigma) -->
<!--     ),  -->
<!--     iter = 41000, warmup = 40000, chains = 4, cores = 4 -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b4.3) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b4.3_half_cauchy) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- posterior_summary(b4.3)[1:3, ] -->
<!-- ``` -->

<!-- ```{r} -->
<!-- posterior_samples(b4.3) %>% -->
<!--   select(-lp__) %>% -->
<!--   cor() %>% -->
<!--   round(digits = 2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 <-  -->
<!--   d2 %>% -->
<!--   mutate(weight_c = weight - mean(weight)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.4 <-  -->
<!--   brm(data = d2, family = gaussian, -->
<!--       height ~ 1 + weight_c, -->
<!--       prior = c(prior(normal(178, 100), class = Intercept), -->
<!--                 prior(normal(0, 10), class = b), -->
<!--                 prior(cauchy(0, 1), class = sigma)), -->
<!--       iter = 46000, warmup = 45000, chains = 4, cores = 4, -->
<!--       control = list(adapt_delta = 0.8,  -->
<!--                      max_treedepth = 10)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b4.4) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- posterior_summary(b4.4)[1:3, ] #%>% -->
<!--   #select(-lp__) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- posterior_samples(b4.4) %>% -->
<!--   select(-lp__) %>% -->
<!--   cor() %>% -->
<!--   round(digits = 2) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pairs(b4.4) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 %>% -->
<!--   ggplot(aes(x = weight, y = height)) + -->
<!--   geom_abline( -->
<!--     intercept = fixef(b4.3)[1], -->
<!--     slope = fixef(b4.3)[2] -->
<!--   ) + -->
<!--   geom_point(shape = 1, size = 2, color = "royalblue") + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post <- posterior_samples(b4.3) -->
<!-- post %>% -->
<!--   slice(1:5) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- N <- 10 -->
<!-- b10 <- brm( -->
<!--   height ~ 1 + weight, -->
<!--   data = d2 %>% -->
<!--     slice(1:N), -->
<!--   family = gaussian, -->
<!--   prior = c( -->
<!--     prior(normal(178, 100), class = Intercept), -->
<!--     prior(normal(0, 10), class = b), -->
<!--     prior(cauchy(0, 1), class = sigma) -->
<!--   ), -->
<!--   iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!-- ) -->

<!-- N <- 50 -->
<!-- b50 <- brm( -->
<!--   height ~ 1 + weight, -->
<!--   data = d2 %>% -->
<!--     slice(1:N), -->
<!--   family = gaussian, -->
<!--   prior = c( -->
<!--     prior(normal(178, 100), class = Intercept), -->
<!--     prior(normal(0, 10), class = b), -->
<!--     prior(cauchy(0, 1), class = sigma) -->
<!--   ), -->
<!--   iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!-- ) -->

<!-- N <- 150 -->
<!-- b150 <- brm( -->
<!--   height ~ 1 + weight, -->
<!--   data = d2 %>% -->
<!--     slice(1:N), -->
<!--   family = gaussian, -->
<!--   prior = c( -->
<!--     prior(normal(178, 100), class = Intercept), -->
<!--     prior(normal(0, 10), class = b), -->
<!--     prior(cauchy(0, 1), class = sigma) -->
<!--   ), -->
<!--   iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!-- ) -->

<!-- N <- 352 -->
<!-- b352 <- brm( -->
<!--   height ~ 1 + weight, -->
<!--   data = d2 %>% -->
<!--     slice(1:N), -->
<!--   family = gaussian, -->
<!--   prior = c( -->
<!--     prior(normal(178, 100), class = Intercept), -->
<!--     prior(normal(0, 10), class = b), -->
<!--     prior(cauchy(0, 1), class = sigma) -->
<!--   ), -->
<!--   iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!-- ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b10) -->
<!-- print(b10) -->

<!-- plot(b50) -->
<!-- print(b50) -->

<!-- plot(b150) -->
<!-- print(b150) -->

<!-- plot(b352) -->
<!-- print(b352) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- post10 <- posterior_samples(b10) -->
<!-- post50 <- posterior_samples(b50) -->
<!-- post150 <- posterior_samples(b150) -->
<!-- post352 <- posterior_samples(b352) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p10 <- -->
<!--   ggplot(data = d2[1:10, ], aes(x = weight, y = height)) + -->
<!--   geom_abline( -->
<!--     intercept = post10[1:20, 1], -->
<!--     slope = post10[1:20, 2], -->
<!--     size = 1 / 3, alpha = .3 -->
<!--   ) + -->
<!--   geom_point(shape = 1, size = 2, color = "royalblue") + -->
<!--   coord_cartesian(xlim = quantile(d2$weight, c(0, 1)), -->
<!--                   ylim = quantile(d2$height, c(0, 1))) + -->
<!--   labs(subtitle = "N = 10") + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->

<!-- p50 <- -->
<!--   ggplot(data = d2[1:50, ], aes(x = weight, y = height)) + -->
<!--   geom_abline( -->
<!--     intercept = post50[1:20, 1], -->
<!--     slope = post50[1:20, 2], -->
<!--     size = 1 / 3, alpha = .3 -->
<!--   ) + -->
<!--   geom_point(shape = 1, size = 2, color = "royalblue") + -->
<!--   coord_cartesian(xlim = quantile(d2$weight, c(0, 1)), -->
<!--                   ylim = quantile(d2$height, c(0, 1))) + -->
<!--   labs(subtitle = "N = 50") + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->

<!-- p150 <- -->
<!--   ggplot(data = d2[1:150, ], aes(x = weight, y = height)) + -->
<!--   geom_abline( -->
<!--     intercept = post150[1:20, 1], -->
<!--     slope = post150[1:20, 2], -->
<!--     size = 1 / 3, alpha = .3 -->
<!--   ) + -->
<!--   geom_point(shape = 1, size = 2, color = "royalblue") + -->
<!--   coord_cartesian(xlim = quantile(d2$weight, c(0, 1)), -->
<!--                   ylim = quantile(d2$height, c(0, 1))) + -->
<!--   labs(subtitle = "N = 150") + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->

<!-- p352 <- -->
<!--   ggplot(data = d2[1:352, ], aes(x = weight, y = height)) + -->
<!--   geom_abline( -->
<!--     intercept = post352[1:20, 1], -->
<!--     slope = post352[1:20, 2], -->
<!--     size = 1 / 3, alpha = .3 -->
<!--   ) + -->
<!--   geom_point(shape = 1, size = 2, color = "royalblue") + -->
<!--   coord_cartesian(xlim = quantile(d2$weight, c(0, 1)), -->
<!--                   ylim = quantile(d2$height, c(0, 1))) + -->
<!--   labs(subtitle = "N = 352") + -->
<!--   theme_bw() + -->
<!--   theme(panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library(gridExtra) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- grid.arrange(p10, p150, p50, p352) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu_at_50 <- -->
<!--   post %>% -->
<!--   transmute(mu_at_50 = b_Intercept + b_weight * 50) -->
<!-- mu_at_50 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu_at_50 %>% -->
<!--   ggplot(aes(x = mu_at_50)) + -->
<!--   geom_density(size = 0, fill = "royalblue") + -->
<!--   #scale_y_continuous(NULL, breaks = NULL) + -->
<!--   labs(x = expression(mu["height | weight = 50"])) + -->
<!--   theme_bw() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mean_hdi(mu_at_50[, 1], .width = c(.89, .95)) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- mu_at_50 %>% -->
<!--   ggplot(aes(x = mu_at_50)) + -->
<!--   geom_density(size = 0, fill = "royalblue") + -->
<!--   stat_pointintervalh(aes(y = 0),  -->
<!--                       point_interval = mode_hdi, .width = .95) + -->
<!--   scale_y_continuous(NULL, breaks = NULL) + -->
<!--   labs(x = expression(mu["height | weight = 50"])) + -->
<!--   theme_classic() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu_at_50 %>% -->
<!--   ggplot(aes(x = mu_at_50)) + -->
<!--   geom_density(size = 0, fill = "royalblue") + -->
<!--   stat_pointintervalh(aes(y = 0), point_interval = mode_hdi, .width = .95) + -->
<!--   labs(x = expression(mu["height | weight = 50"])) + -->
<!--   theme_bw() -->
<!--   #) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu <- fitted(b4.3, summary = F) -->
<!-- str(mu) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- weight_seq <- tibble(weight = seq(25, 70, by = 1)) -->

<!-- mu <- fitted(b4.3, summary = F, newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   rowid_to_column() -->

<!-- mu -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu <-  -->
<!--   mu %>% -->
<!--   gather(key, value, V1:V46) %>%  -->
<!--   mutate(key = str_extract(key, "\\d+") %>% as.integer()) %>% -->
<!--   rename(weight = key, height = value) %>% -->
<!--   mutate(weight = weight + 24) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 %>% -->
<!--   ggplot(aes(x = weight, y = height)) + -->
<!--   geom_point( -->
<!--     data = mu %>% filter(rowid < 101), -->
<!--     alpha = .1) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- mu_summary <-  -->
<!--   fitted(b4.3, newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 %>% -->
<!--   ggplot(aes(x = weight, y = height)) +  -->
<!--   geom_ribbon( -->
<!--     data = mu_summary, -->
<!--     aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--     fill = "grey70" -->
<!--   ) + -->
<!--   geom_line( -->
<!--     data = mu_summary, -->
<!--     aes(y = Estimate) -->
<!--   ) + -->
<!--   geom_point(color = "navyblue", shape = 1, size = 1.5, alpha = 2 / 3) + -->
<!--   coord_cartesian(xlim = range(d2$weight)) + -->
<!--   theme( -->
<!--     text = element_text(family = "Times"), -->
<!--     panel.grid = element_blank() -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- weight_seq <- tibble(weight = seq(25, 70, by = 1)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- pred_height <- -->
<!--   predict( -->
<!--     b4.3, -->
<!--     newdata = weight_seq -->
<!--   ) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq) -->

<!-- pred_height %>% slice(1:6) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- d2 %>% -->
<!--   ggplot(aes(x = weight)) + -->
<!--   geom_ribbon( -->
<!--     data = pred_height, -->
<!--     aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--     fill = "grey83" -->
<!--   ) + -->
<!--   geom_ribbon( -->
<!--     data = mu_summary, -->
<!--     aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--     fill = "grey70" -->
<!--   ) + -->
<!--   geom_line(data = mu_summary, aes(y = Estimate)) + -->
<!--   geom_point( -->
<!--     aes(y = height), -->
<!--     color = "navyblue", -->
<!--     shape = 1, size = 1.5, alpha = 2 /3 -->
<!--   ) + -->
<!--   coord_cartesian( -->
<!--     xlim = range(d2$weight), -->
<!--     ylim = range(d2$height) -->
<!--   ) + -->
<!--   theme( -->
<!--     text = element_text(family = "Times"), -->
<!--     panel.grid = element_blank() -->
<!--   ) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- d %>% glimpse() -->
<!-- ``` -->
<!-- ```{r} -->
<!-- d <-  -->
<!--   d %>% -->
<!--   mutate(weight_s = (weight - mean(weight)) / sd(weight)) -->
<!-- d -->
<!-- ``` -->


<!-- ```{r} -->
<!-- b4.5 <-  -->
<!--   brm( -->
<!--     height ~ 1 + weight_s + I(weight_s^2), -->
<!--     data = d, -->
<!--     prior = c( -->
<!--       prior(normal(178, 100), class = Intercept), -->
<!--       prior(normal(0, 10), class = b), -->
<!--       prior(cauchy(0, 1), class = sigma) -->
<!--     ), -->
<!--     iter = 2000, warmup = 1000, chains = 4, cores = 4 -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- plot(b4.5) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- print(b4.5) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- weight_seq <- tibble(weight_s = seq(from = -2.5, to = 2.5, length.out = 30)) -->

<!-- fitd_quad <- -->
<!--   fitted(b4.5,  -->
<!--          newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq) -->

<!-- pred_quad <- -->
<!--   predict(b4.5,  -->
<!--           newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq)   -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot(data = d,  -->
<!--        aes(x = weight_s, y = height)) + -->
<!--   geom_ribbon(data = pred_quad,  -->
<!--               aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--               fill = "grey83") + -->
<!--   geom_ribbon(data = fitd_quad,  -->
<!--               aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--               fill = "grey70") + -->
<!--   geom_line(data = fitd_quad,  -->
<!--             aes(y = Estimate), size = 1/4) + -->
<!--   geom_point(color = "navyblue", shape = 1, size = 1.5, alpha = 1/3) + -->
<!--   coord_cartesian(xlim = range(d$weight_s)) + -->
<!--   theme(text = element_text(family = "Times"), -->
<!--         panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- b4.6 <-  -->
<!--   brm(data = d, family = gaussian, -->
<!--       height ~ 1 + weight_s + I(weight_s^2) + I(weight_s^3), -->
<!--       prior = c(prior(normal(178, 100), class = Intercept), -->
<!--                 prior(normal(0, 10), class = b), -->
<!--                 prior(cauchy(0, 1), class = sigma)), -->
<!--       iter = 2000, warmup = 1000, chains = 4, cores = 4) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fitd_cub <- -->
<!--   fitted(b4.6,  -->
<!--          newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq) -->

<!-- pred_cub <- -->
<!--   predict(b4.6,  -->
<!--           newdata = weight_seq) %>% -->
<!--   as_tibble() %>% -->
<!--   bind_cols(weight_seq)  -->

<!-- ggplot(data = d,  -->
<!--        aes(x = weight_s, y = height)) + -->
<!--   geom_ribbon(data = pred_cub,  -->
<!--               aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--               fill = "grey83") + -->
<!--   geom_ribbon(data = fitd_cub,  -->
<!--               aes(y = Estimate, ymin = Q2.5, ymax = Q97.5), -->
<!--               fill = "grey70") + -->
<!--   geom_line(data = fitd_cub,  -->
<!--             aes(y = Estimate),  -->
<!--             size = 1/4) + -->
<!--   geom_point(color = "navyblue", shape = 1, size = 1.5, alpha = 1/3) + -->
<!--   coord_cartesian(xlim = range(d$weight_s)) + -->
<!--   theme(text = element_text(family = "Times"), -->
<!--         panel.grid = element_blank()) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- loo(b4.5, b4.6) -->
<!-- ``` -->

