---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

d <- 
  tibble(species = c("afarensis", "africanus", "habilis", "boisei", "rudolfensis", "ergaster", "sapiens"), 
         brain   = c(438, 452, 612, 521, 752, 871, 1350), 
         mass    = c(37.0, 35.5, 34.5, 41.5, 55.5, 61.0, 53.5))
d
```

```{r}
install.packages("rcartocolor", dependencies = T)
library(rcartocolor)
```

```{r}
library(ggrepel)

d %>%
  ggplot(aes(x = mass, y = brain, label = species)) +
  geom_point(color = carto_pal(7, "BurgYl")[5]) +
  geom_text_repel(
    size = 3, seed = 438,
    color = carto_pal(7, "BurgYl")[7], 
    family = "Courier"
  ) +
  labs(
    x = "body mass (kg)",
    y = "brain volume (cc)", 
    subtitle = "Average brain volume by body\nmass for six hominin species"
  ) + 
  theme_classic() +
  theme(
    text = element_text(family = "Courier"),
    panel.background = element_rect(fill = alpha(carto_pal(7, "BurgYl")[3], 1 / 4))
  )
```

```{r}

```

```{r}
library(broom)
fit_lm <- function(model, formula) {
  model <- lm(data = d, formula = formula)
}

fits <-
  tibble(
    model = str_c("b6.", 1:6),
    formula = c(
      "brain ~ mass",
      "brain ~ mass + I(mass^2)",
      "brain ~ mass + I(mass^2) + I(mass^3)",
      "brain ~ mass + I(mass^2) + I(mass^3) + I(mass^4)",
      "brain ~ mass + I(mass^2) + I(mass^3) + I(mass^4) + I(mass^5)",
      "brain ~ mass + I(mass^2) + I(mass^3) + I(mass^4) + I(mass^5) + I(mass^6)"
    )
  ) %>%
  mutate(fit = map2(model, formula, fit_lm)) %>%
  mutate(
    tidy = map(fit, tidy),
    glance = map(fit, glance)
  )
print(fits)
```

```{r}
fits <-
  fits %>%
  mutate(r2 = glance %>% map_dbl("r.squared")) %>%
  mutate(r2_text = round(r2, digits = 2) %>% as.character() %>% str_replace(., "0.", "."))
```

```{r}
fits %>% 
  ggplot(aes(x = r2, y = formula, label = r2_text)) +
  geom_text(color = carto_pal(7, "BurgYl")[7], size = 3.5)  +
  labs(x = expression(italic(R)^2), y = NULL) +
  scale_x_continuous(limits = 0:1, breaks = 0:1) +
  theme_classic() +
  theme(axis.text.y  = element_text(hjust = 0),
        axis.ticks.y = element_blank(),
        text         = element_text(family = "Courier"),
        panel.background = element_rect(fill = alpha(carto_pal(7, "BurgYl")[3], 1/4)))
```


```{r}
fits %>%
  unnest(tidy) %>%
  mutate_if(is.double, round, digits = 1) %>%
  complete(term = distinct(., term), model) %>%
  spread(key = term, value = estimate) %>%
  select(model, `(Intercept)`, mass, everything())
```




```{r}
p <-
  d %>%
  ggplot(aes(x = mass, y = brain)) +
  geom_point(color = carto_pal(7, "BurgYl")[7]) +
  scale_x_continuous(limits = c(33, 62)) +
  coord_cartesian(ylim = c(300, 1500)) +
  labs(
    x = "body mass (kg)",
    y = "brain volume (cc)"
  ) +
  theme_classic() +
  theme(
    text = element_text(family = "Courier"),
    panel.background = element_rect(fill = alpha(carto_pal(7, "BurgYl")[3], 1 / 4))
  )
```

```{r}
p1 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ x
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = .49")))

p2 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ poly(x, 2)
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = .54")))

p3 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ poly(x, 3)
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = .68")))

p4 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ poly(x, 4)
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = .81")))

p5 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ poly(x, 5)
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = .99")))

p6 <-
  p +
  stat_smooth(
    method = "lm",
    fullrange = TRUE,
    level = .89,
    color = carto_pal(7, "BurgYl")[6], 
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2,
    alpha = 1 / 3,
    formula = y ~ poly(x, 6)
  ) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = 1")))

library(gridExtra)
grid.arrange(p1, p2, p3, p4, p5, p6, ncol = 3)
```

```{r}
b6.7 <- lm(brain ~ 1, data = d)
summary(b6.7)
```

```{r}
glance(b6.7)
```

```{r}
p +
  stat_smooth(
    method = "lm", fullrange = TRUE, level = .89,
    color = carto_pal(7, "BurgYl")[6],
    fill = carto_pal(7, "BurgYl")[6],
    size = 1 / 2, alpha = 1 / 3,
    formula = y ~ 1) +
  ggtitle(NULL, subtitle = expression(paste(italic(R)^2, " = 0")))
```


```{r}
d %>%
  filter(row_number() != 2)
```


```{r}
nd <- tibble(mass = c(30, 70))
make_lines <- function(row) {
  my_fit <-
    d %>%
    filter(row_number() != row) %>%
    lm(formula = brain ~ mass)
  predict(my_fit, nd) %>%
    as_tibble() %>%
    rename(brain = value) %>%
    bind_cols(nd)
}
```


```{r}
lines <- 
  tibble(row = 1:7) %>%
  mutate(p = map(row, make_lines)) %>%
  unnest(p)
```

```{r}
p +
  scale_x_continuous(expand = c(0, 0)) +
  geom_line(
    data = lines, 
    aes(x = mass, y = brain, group = row),
    color = carto_pal(7, "BurgYl")[6], alpha = 1 / 2, size = 1 / 2
  )
```


```{r}
nd <- tibble(mass = seq(30, 65, length.out = 200))
make_lines <- function(row) {
  my_fit <-
    d %>%
    filter(row_number() != row) %>%
    lm(formula = brain ~ mass + I(mass^2) + I(mass^3) + I(mass^4) + I(mass^5) + I(mass^6))
  predict(my_fit, nd) %>%
    as_tibble() %>%
    rename(brain = value) %>%
    bind_cols(nd)
}
```

```{r}
lines <- 
  tibble(row = 1:7) %>%
  mutate(p = map(row, make_lines)) %>%
  unnest(p)
```

```{r}
p +
  scale_x_continuous(expand = c(0, 0)) +
  geom_line(
    data = lines, 
    aes(x = mass, y = brain, group = row),
    color = carto_pal(7, "BurgYl")[6], alpha = 1 / 2, size = 1 / 2
  )
```

```{r}
weatherperson <-
  tibble(day        = 1:10,
         prediction = rep(c(1, 0.6), times = c(3, 7)),
         observed   = rep(c(1, 0), times = c(3, 7))) 

newcomer <-
  tibble(day        = 1:10,
         prediction = 0,
         observed   = rep(c(1, 0), times = c(3, 7)))
```

```{r}
weatherperson %>%
  bind_rows(newcomer) %>%
  mutate(
    person = rep(c("weatherperson", "newcomer"), each = n() / 2),
    hit = ifelse(prediction == observed, 1, 1 - prediction - observed)
  ) %>% 
  group_by(person, hit) %>%
  count() %>% 
  ungroup() %>%
  mutate(
    power = hit ^ n,
    term = rep(letters[1:2], times = 2)
  ) %>%
  select(person, term, power) %>%
  spread(key = term, power) %>%
  mutate(probability_correct_sequence = a * b)
```

```{r}
tibble(
  place  = c("McElreath's house", "Abu Dhabi"),
  p_rain = c(.3, .01)
) %>% 
  mutate(p_shine = 1 - p_rain) %>% 
  group_by(place) %>% 
  mutate(H_p = (p_rain * log(p_rain) + p_shine * log(p_shine)) %>% mean() * -1)
```


```{r}
p <- c(.5, .1, .1, .1, .1, .1)
-sum(p * log(p))
```

```{r}
t <- 
  tibble(p_1  = .3,
         p_2  = .7,
         q_1  = seq(from = .01, to = .99, by = .01)) %>% 
  mutate(q_2  = 1 - q_1) %>%
  mutate(d_kl = (p_1 * log(p_1 / q_1)) + (p_2 * log(p_2 / q_2)))

(t)

```


```{r}
t %>% 
  ggplot(aes(x = q_1, y = d_kl)) +
  geom_vline(xintercept = .3, color = carto_pal(7, "BurgYl")[5], linetype = 2) +
  geom_line(color = carto_pal(7, "BurgYl")[7], size = 1.5) +
  annotate(geom = "text", x = .4, y = 1.5, label = "q = p",
           color = carto_pal(7, "BurgYl")[5], family = "Courier", size = 3.5) +
  labs(x = "q[1]",
       y = "Divergence of q from p") +
  theme_classic() +
  theme(text = element_text(family = "Courier"),
        panel.background = element_rect(fill = alpha(carto_pal(7, "BurgYl")[3], 1/4)))
```

```{r}
lm(brain ~ mass, data = d) %>%
  logLik() * -2
```

```{r}
d <-
  d %>% 
  mutate(mass_s = (mass - mean(mass)) / sd(mass))
d
```

```{r}
library(brms)
```

```{r}
inits <- list(
  Intercept = mean(d$brain), 
  mass_s = 0,
  sigma = sd(d$brain)
)

inits_list <-list(inits, inits, inits, inits)
inits_list
```


```{r}
b6.8 <-
  brm(
    brain ~ 1 + mass_s,
    data = d,
    family = gaussian,
    prior = c(
      prior(normal(0, 1000), class = Intercept),
      prior(normal(0, 1000), class = b),
      prior(cauchy(0, 10), class = sigma)
    ),
    iter = 2000, warmup = 1000, chains = 4, cores = 4,
    inits = inits_list
  )
```

```{r}
print(b6.8)
```

```{r}
dfLL <-
  b6.8 %>%
  log_lik() %>%
  as_tibble()
dfLL %>%
  glimpse()
```

```{r}
dfLL <-
  dfLL %>%
  mutate(sums = rowSums(.),
         deviance = -2 * sums)
dfLL
```

```{r}
library(tidybayes)
dfLL %>%
  ggplot(aes(x = deviance, y = 0)) +
  geom_halfeyeh(
    point_interval = median_qi, .width = .95,
    fill = carto_pal(7, "BurgYl")[5],
    color = carto_pal(7, "BurgYl")[7]
  ) +
  scale_x_continuous(
    breaks = quantile(dfLL$deviance, c(.025, .5, .975)),
    labels = quantile(dfLL$deviance, c(.025, .5, .975)) %>% round(1)
  )
```

```{r}
library(rethinking)

N <- 20
kseq <- 1:5

n_sim <- 1e3
n_cores <- 4

sapply(kseq, function(k) {
  print(k)
  r <- mcreplicate(n_sim, sim.train.test(N = N, k = k),
                   mc.cores = n_cores);
  c(mean(r[1, ]), mean(r[2, ]), sd(r[1, ]), sd(r[2, ]))
})
```


```{r}
data(cars)

b <- 
  brm(data = cars, family = gaussian,
      dist ~ 1 + speed,
      prior = c(prior(normal(0, 100), class = Intercept),
                prior(normal(0, 10), class = b),
                prior(uniform(0, 30), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4)
```


```{r}
waic(b)
```


```{r}
library(rethinking)
data(milk)

d <- 
  milk %>%
  filter(complete.cases(.))
rm(milk)

d <-
  d %>%
  mutate(neocortex = neocortex.perc / 100)
d
```

```{r}
dim(d)
detach(package:rethinking, unload = T)
library(brms)
```

```{r}
inits <- list(
  Intercept = mean(d$kcal.per.g),
  sigma = sd(d$kcal.per.g)
)

inits_list <- list(inits, inits, inits, inits)
```


```{r}
inits <- list(Intercept = mean(d$kcal.per.g),
              sigma     = sd(d$kcal.per.g))

inits_list <-list(inits, inits, inits, inits)

b6.11 <- 
  brm(data = d, family = gaussian,
      kcal.per.g ~ 1,
      prior = c(prior(uniform(-1000, 1000), class = Intercept),
                prior(uniform(0, 100), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      inits = inits_list)

inits <- list(Intercept = mean(d$kcal.per.g),
              neocortex = 0,
              sigma     = sd(d$kcal.per.g))
b6.12 <- 
  brm(data = d, family = gaussian,
      kcal.per.g ~ 1 + neocortex,
      prior = c(prior(uniform(-1000, 1000), class = Intercept),
                prior(uniform(-1000, 1000), class = b),
                prior(uniform(0, 100), class = sigma)),
      iter = 2000, warmup = 1000, chains = 4, cores = 4,
      inits = inits_list)

inits <- list(Intercept   = mean(d$kcal.per.g),
              `log(mass)` = 0,
              sigma       = sd(d$kcal.per.g))
b6.13 <-
  update(b6.12, 
         newdata = d,
         formula = kcal.per.g ~ 1 + log(mass),
         inits   = inits_list)

inits <- list(Intercept   = mean(d$kcal.per.g),
              neocortex   = 0,
              `log(mass)` = 0,
              sigma       = sd(d$kcal.per.g))
b6.14 <- 
  update(b6.13, 
         newdata = d,
         formula = kcal.per.g ~ 1 + neocortex + log(mass),
         inits   = inits_list)
```


```{r}
waic(b6.11, b6.12, b6.13, b6.14)
```

```{r}
w_b6.11 <- waic(b6.11)
w_b6.12 <- waic(b6.12)
w_b6.13 <- waic(b6.13)
w_b6.14 <- waic(b6.14)
loo_compare(w_b6.11, w_b6.12, w_b6.13, w_b6.14)
```


```{r}
model_weights(b6.11, b6.12, b6.13, b6.14, weights = "waic") %>%
  as_tibble()
```

```{r}
tidy(b6.14)
```











