---
title: "Estimating Non-Linear Models with brms"
date: 2020-05-22
output: html_notebook
---

```{r}
library(tidyverse)
library(brms)
```


# A Simple Non-Linear Model
```{r}
b <- c(2, 0.75)
x <- rnorm(100)
y <- rnorm(100, mean = b[1] * exp(b[2] * x))
dat1 <- tibble(x, y)
dat1
```


```{r}
prior1 <- 
  prior(normal(1, 2), nlpar = "b1") +
  prior(normal(0, 2), nlpar = "b2")
prior1
```

```{r}
fit1 <- 
  brm(
    bf(y ~ b1 * exp(b2 * x), b1 + b2 ~ 1, nl = TRUE),
    data = dat1, prior = prior1
  )
```

```{r}
summary(fit1)
```

```{r}
plot(fit1)
```


```{r}
plot(conditional_effects(fit1), points = TRUE)
```

```{r}
fit2 <- brm(y ~ x, data = dat1)
summary(fit2)
```


```{r}
pp_check(fit1)
pp_check(fit2)
```

```{r}
loo(fit1, fit2)
```


# A Real-World Non-Linear model

```{r}
loss <- read.csv("https://paul-buerkner.github.io/data/loss.csv")
loss
```

```{r}
loss %>% 
  ggplot(aes(dev, cum, color = factor(AY))) +
  geom_point() #+
  # facet_wrap(~AY)
```

```{r}
fit_loss <- brm(
  bf(cum ~ ult * (1 - exp(-(dev/theta)^omega)),
     ult ~ 1 + (1 | AY),
     omega ~ 1,
     theta ~ 1,
     nl = TRUE),
  data = loss, family = gaussian(),
  prior = c(
    prior(normal(5000, 1000), nlpar = "ult"),
    prior(normal(1, 2), nlpar = "omega"),
    prior(normal(45, 10), nlpar = "theta")
  ),
  control = list(adapt_delta = 0.9)
)
```


```{r}
summary(fit_loss)
```

```{r}
plot(fit_loss, N = 3, ask = FALSE)
```

```{r}
conditional_effects(fit_loss)
```

```{r}
conditions <- data.frame(AY = unique(loss$AY))
rownames(conditions) <- unique(loss$AY)
conditions
```

```{r}
me_loss <- conditional_effects(
  fit_loss, conditions = conditions,
  re_formula = NULL, method = "predict"
)
plot(me_loss, ncol = 5, points = TRUE)
```

```{r}
predict(fit_loss, re_formula = NULL)
```


# Advanced Item-Response Models

```{r}
inv_logit <- function(x) 1 / (1 + exp(-x))
ability <- rnorm(300)
p <- 0.33 + 0.67 * inv_logit(ability)
answer <- ifelse(runif(300, 0, 1) < p, 1, 0)
dat_ir <- data.frame(ability, answer)
```

```{r}
fit_ir1 <- brm(answer ~ ability, data = dat_ir, family = bernoulli())
```

```{r}
summary(fit_ir1)
```



```{r}
fit_ir2 <- brm(
  bf(answer ~ 0.33 + 0.67 * inv_logit(eta),
     eta ~ ability, nl = TRUE),
  data = dat_ir, family = bernoulli("identity"),
  prior = prior(normal(0, 5), nlpar = "eta")
)
```


```{r}
summary(fit_ir2)
```

```{r}
plot(conditional_effects(fit_ir2), points = TRUE)
```


```{r}
loo(fit_ir1, fit_ir2)
```


```{r}
fit_ir3 <- brm(
  bf(answer ~ guess + (1 - guess) * inv_logit(eta), 
    eta ~ 0 + ability, guess ~ 1, nl = TRUE),
  data = dat_ir, family = bernoulli("identity"), 
  prior = c(
    prior(normal(0, 5), nlpar = "eta"),
    prior(beta(1, 1), nlpar = "guess", lb = 0, ub = 1)
  )
)
```

```{r}
summary(fit_ir3)
```

```{r}
plot(fit_ir3)
```

```{r}
plot(conditional_effects(fit_ir3), points = TRUE)
```


















