---
title: "R notebook"
output: html_notebook
---

# Ch 02
```{r}
x <- seq(-pi, pi, length = 50)
y <- x

f <- outer(x, y, function(x, y) {cos(y) / (1 + x^2)})
contour(x, y, f)
```

```{r}
fa <- (f - t(f)) / 2
contour(x, y, fa, nlevels = 15)
```

```{r}
image(x, y, fa)
```

```{r}
persp(x, y, fa, theta = 30, phi = 45)
```

```{r}
A <- matrix(1:16, nrow =4)
A
dim(A)
```

```{r}
mtcars
plot(mpg ~ cyl, data = mtcars)
```

```{r}
cylinders <- as.factor(mtcars$cyl)
mpg <- mtcars$mpg
plot(cylinders, mpg)
```

```{r}
library(tidyverse)
mtcars %>%
  ggplot(aes(x = as.factor(cyl), y = mpg)) +
  geom_boxplot()
```

```{r}
mtcars %>%
  ggplot(aes(x = mpg)) +
  geom_histogram()
```


```{r}
library(GGally)
mtcars %>%
  select(1:3) %>%
  ggpairs()
```

```{r}
plot(mtcars$disp, mpg)
identify(mtcars$disp, mpg)
```



```{r}
summary(mtcars)
```

```{r, echo=FALSE}
curve(82*x, from=0, to=10, xlab="flexibility", ylab="MSE", col="white")  
curve(300*cos(x/3)+500+x^3/3, add=TRUE, col="red", lwd=2)  # test error
curve(x^3/3, add=TRUE, col="orange", lwd=2)                # variance
curve(0*x+250, add=TRUE, col="gray", lwd=2)                # irreducible error
curve(300*cos(x/3)+350, add=TRUE, col="green", lwd=2)      # bias
curve(225*cos(x/3)+450, add=TRUE, col="blue", lwd=2)       # train error
```