---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(ISLR)
library(corrplot)
(Smarket)
```



```{r}
plot(Smarket)
```

```{r}
cor(Smarket)
```

```{r}
corrplot(cor(Smarket[, -9]))
```

```{r}
Smarket %>%
  pull(Volume) %>%
  plot()
```

```{r}
glm_fit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
               data = Smarket, family= binomial)
summary(glm_fit)
```

```{r}
coef(glm_fit)
summary(glm_fit)$coef
```

```{r}
glm_probs <- predict(glm_fit, type = "response")
glm_probs[1:10]
contrasts(Smarket$Direction)
```

```{r}
glm_pred = rep("Down", 1250)
glm_pred[glm_probs > .5] = "Up"
```

```{r}
table(glm_pred, Smarket$Direction)
```

```{r}
(507 + 145) / 1250
mean(glm_pred == Smarket$Direction)
```

```{r}
train <- (Smarket$Year < 2005)
Smarket.2005 <- Smarket[!train, ]
Smarket.2005
Direction.2005 <- Smarket$Direction[!train]
```

```{r}
sum(train)
```


```{r}
glm_fit <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
               data = Smarket, family = binomial, subset = train)
glm.probs = predict(glm_fit, Smarket.2005, type = "response")
```

```{r}
glm.pred = rep("Down", 252)
glm.pred[glm.probs > .5] <- "Up"
table(glm.pred, Direction.2005)
```

```{r}
mean(glm.pred == Direction.2005)
```

```{r}
summary(glm_fit)
```

```{r}
glm.fit2 <- glm(Direction ~ Lag1 + Lag2, 
                data = Smarket, family = binomial,
                subset = train)
glm.probs = predict(glm.fit2, Smarket.2005, type = "response")
glm.pred = rep("Down", 252)
glm.pred[glm.probs > .5] <- "Up"
table(glm.pred, Direction.2005)
mean(glm.pred == Direction.2005)
106 / (106 + 76)
```

```{r}
predict(glm.fit2, newdata = data.frame(Lag1 = c(1.2, 1.5), Lag2 = c(1.1, -0.8)), 
        type = "response")
```

```{r}
library(MASS)
lda.fit <- lda(Direction ~ Lag1 + Lag2,
               data = Smarket, subset = train)
lda.fit
```

```{r}
plot(lda.fit)
```

```{r}
lda.pred <- predict(lda.fit, Smarket.2005)
str(lda.pred)
```

```{r}
lda.class = lda.pred$class
table(lda.class, Direction.2005)
```

```{r}
sum(lda.pred$posterior[, 1] >= .5)
sum(lda.pred$posterior[, 1] < .5)
```

```{r}
lda.pred$posterior[1:20, 1]
```

```{r}
lda.class[1:20]
```

```{r}
qda.fit <- qda(Direction ~ Lag1 + Lag2, 
               data = Smarket,
               subset = train)
qda.fit
```

```{r}
qda.class <- predict(qda.fit, Smarket.2005)$class
table(qda.class, Direction.2005)
mean(qda.class == Direction.2005)
```

```{r}
library(class)
train.X <- cbind(Smarket$Lag1, Smarket$Lag2)[train, ]
test.X <- cbind(Smarket$Lag1, Smarket$Lag2)[!train, ]
train.Direction = Smarket$Direction[train]
set.seed(1)
knn.pred = knn(train.X, test.X, train.Direction, k = 1)
table(knn.pred, Direction.2005)
(83 + 43) / 252
```

```{r}
train.X <- cbind(Smarket$Lag1, Smarket$Lag2)[train, ]
test.X <- cbind(Smarket$Lag1, Smarket$Lag2)[!train, ]
train.Direction = Smarket$Direction[train]
set.seed(1)
knn.pred = knn(train.X, test.X, train.Direction, k = 3)
table(knn.pred, Direction.2005)
```

4.6.6
```{r}
dim(Caravan)
summary(Caravan$Purchase)
```

```{r}
standardized.X = scale(Caravan[, -86])
var(Caravan[, 1])
```

```{r}
standardized.X
```

```{r}
test = 1:1000
train.X = standardized.X[-test, ]
test.X = standardized.X[test, ]
train.Y = Caravan$Purchase[-test]
test.Y = Caravan$Purchase[test]
set.seed(1)
knn.pred = knn(train.X, test.X, train.Y, k = 1)
mean(test.Y != knn.pred)
mean(test.Y != "No")
```

```{r}
table(knn.pred, test.Y)
```

