---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ISLR)
set.seed(1)
train <- sample(392, 196)
```

```{r}
lm.fit <- lm(mpg ~ horsepower, data = Auto, subset = train)
mean(((mpg - predict(lm.fit, Auto))[-train])^2)

lm.fit2 <- lm(mpg~poly(horsepower, 2), data = Auto, subset = train)
mean((mpg - predict(lm.fit2, Auto))[-train]^2)

lm.fit3 <- lm(mpg~poly(horsepower, 3), data = Auto, subset = train)
mean((mpg - predict(lm.fit3, Auto))[-train]^2)
```

```{r}

```

```{r}
glm.fit <- glm(mpg ~ horsepower, data = Auto)
coef(glm.fit)

lm.fit <- lm(mpg ~ horsepower, data = Auto)
coef(lm.fit)
```

```{r}
library(boot)
glm.fit <- glm(mpg ~ horsepower, data = Auto)
cv.err = cv.glm(Auto, glm.fit)
cv.err$delta
```

```{r}
cv.error <- rep(0, 5)
for (i in 1:5) {
  glm.fit <- glm(mpg ~ poly(horsepower, i), data = Auto)
  cv.error[i] = cv.glm(Auto, glm.fit)$delta[1]
}
cv.error
```

```{r}
cv.error.10 <- rep(0, 10)
for (i in 1:10) {
  glm.fit <- glm(mpg ~ poly(horsepower, i), data = Auto)
  cv.error.10[i] = cv.glm(Auto, glm.fit, K = 10)$delta[1]
}
cv.error.10
```







```{r}
boot.fn <- function(data, index) {
  return(coef(lm(mpg ~ horsepower, data = data, subset = index)))
}
```

```{r}
boot.fn(Auto, 1:392)
```

```{r}
set.seed(1)
boot.fn(Auto, sample(392, 392, replace = T))
boot.fn(Auto, sample(392, 392, replace = T))
```

```{r}
boot(Auto, boot.fn, 1000)
```


```{r}
boot.fn <- function(data, index) {
  return(coef(lm(mpg ~ horsepower + I(horsepower ^2), data = data, subset = index)))
}

boot.fn(Auto, 1:392)


boot(Auto, boot.fn, 1000)
```


```{r}
summary(lm(mpg ~ horsepower + I(horsepower^2), data = Auto, subset = 1:392))
```






























