---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ISLR)
names(Hitters)
dim(Hitters)
sum(is.na(Hitters$Salary))
```

```{r}
Hitters <- na.omit(Hitters)
dim(Hitters)
complete.cases(Hitters)
```

```{r}
library(leaps)
regfit.full <- regsubsets(Salary ~ ., Hitters, nvmax = 22)
reg.summary = summary(regfit.full)
```

```{r}
reg.summary$cp
```

```{r}
par(mfrow = c(2, 2))
plot(reg.summary$rss, xlab = "Number of Variables", ylab = "RSS", type = "l")
plot(reg.summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")
plot(reg.summary$cp, xlab = "Number of Variables", ylab = "Cp", type = "l")
plot(reg.summary$bic, xlab = "Number of Variables", ylab = "bic", type = "l")
pos <- which.min(reg.summary$bic)
points(pos, reg.summary$bic[pos], col = "red", cex = 2, pch = 20)
```

```{r}
plot(regfit.full, scale ="r2")
plot(regfit.full, scale ="adjr2")
plot(regfit.full, scale ="Cp")
plot(regfit.full, scale ="bic")
```

```{r}
regfit.fwd = regsubsets(Salary ~ . , data = Hitters, nvmax = 19, method = "forward")
summary(regfit.fwd)
regfit.bwd = regsubsets(Salary ~ . , data = Hitters, nvmax = 19, method = "backward")
summary(regfit.bwd)
```

```{r}
set.seed(1)
train <- sample(c(TRUE, FALSE), nrow(Hitters), rep = TRUE)
test <- !train
train
test
```

```{r}
regfit.best = regsubsets(Salary ~ ., data = Hitters[train, ], nvmax = 19)
test.mat = model.matrix(Salary ~ ., data = Hitters[test, ])
var.errors = rep(NA, 19)
for (i in 1:19) {
  coefi = coef(regfit.best, id = i)
  pred = test.mat[, names(coefi)] %*% coefi
  var.errors[i] = mean((Hitters$Salary[test] - pred) ^2)
}
plot(var.errors)
```

```{r}
x <- model.matrix(Salary ~ ., Hitters)[, -1]
y <- Hitters$Salary
x
```

```{r}
install.packages("glmnet")
library(glmnet)
```

```{r}
grid <- 10^seq(10, -2, length = 100)
ridge.mod <- glmnet(x, y, alpha = 0, lambda = grid)
```

```{r}
grid <- 10^seq(10, -2, length = 100)
lasso.mod <- glmnet(x, y, alpha = 1, lambda = grid)
```

```{r}
ridge.mod$lambda[50]
coef(ridge.mod)[, 50]
```

