---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

# part 1

```{r}
x <- seq(-1, 1, by = 0.2)

y <- x^3

qplot(x, y)
```

```{r}
x <- c(1, 2, 2, 2, 3, 3)
qplot(x, binwidth = 1)

x2 <- c(1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4)
qplot(x2, binwidth = 1)

```


```{r}
roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE)
  sum(dice)
}

roll2 <- function(bones = 1:6) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice)
}

roll2()


test <- function(bones) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice)
}
```

```{r}
rolls <- replicate(10000, roll())
qplot(rolls, binwidth = 1)
```


```{r}
roll <- function() {
  die <- 1:6
  dice <- sample(
    die, size = 2, replace = TRUE,
    prob = c(1/8, 1/8, 1/8, 1/8, 1/8, 3/8)
  )
  sum(dice)
}
```

```{r}
rolls <- replicate(10000, roll())
qplot(rolls, binwidth = 1)
```

```{r}
die <- c(1, 2, 3, 4, 5, 6)
die
is.vector(die)
```

```{r}
five <- 5
five
is.vector(five)
length(five)
length(die)
```

```{r}
typeof(die)
```

```{r}
text <- c("Hello", "World")
text
```

```{r}
3 > 4

logic <- c(TRUE, FALSE, TRUE)
logic
typeof(logic)
typeof(F)
```
```{r}
hand <- c("ace", "king", "queen", "jack", "ten")
hand
typeof(hand)
```


```{r}
names(die) <- c("one", "two", "three", "four", "five", "six")
die
```


```{r}
dim(die) <- c(2, 3)
die
```
```{r}
m <- matrix(die, nrow = 2)
m <- matrix(die, nrow = 2, byrow = TRUE)
m
```

```{r}
ar <- array(c(11:14, 21:24, 31:34), dim = c(2, 2, 3))
ar
```

```{r}
hand1 <- c("ace", "king", "queen", "jack", "ten", "spades", "spades", 
  "spades", "spades", "spades")
matrix(hand1, nrow = 5)
```

```{r}
dim(die) <- c(2, 3)
typeof(die)
class(die)
```

```{r}
now <- Sys.time()
now
typeof(now)
class(now)
unclass(now)
mil <- 1000000
class(mil) <- c("POSIXct")
mil
```

```{r}
gender <- factor(c("male", "female", "female", "male"))
typeof(gender)
attributes(gender)
unclass(gender)
as.character(gender)
```

```{r}
list1 <- list(100:130, "R", list(TRUE, FALSE))
list1
```




# Part 2

```{r}
df <- data.frame(
  face = c("ace", "two", "six"), 
  suit = c("clubs", "clubs", "clubs"),
  value = c(1, 2, 3),
  stringsAsFactors = FALSE
)
df
typeof(df)
class(df)
str(df)
```

```{r}
deck <- data.frame(
  face = c("king", "queen", "jack", "ten", "nine", "eight", "seven", "six",
    "five", "four", "three", "two", "ace", "king", "queen", "jack", "ten", 
    "nine", "eight", "seven", "six", "five", "four", "three", "two", "ace", 
    "king", "queen", "jack", "ten", "nine", "eight", "seven", "six", "five", 
    "four", "three", "two", "ace", "king", "queen", "jack", "ten", "nine", 
    "eight", "seven", "six", "five", "four", "three", "two", "ace"),  
  suit = c("spades", "spades", "spades", "spades", "spades", "spades", 
    "spades", "spades", "spades", "spades", "spades", "spades", "spades", 
    "clubs", "clubs", "clubs", "clubs", "clubs", "clubs", "clubs", "clubs", 
    "clubs", "clubs", "clubs", "clubs", "clubs", "diamonds", "diamonds", 
    "diamonds", "diamonds", "diamonds", "diamonds", "diamonds", "diamonds", 
    "diamonds", "diamonds", "diamonds", "diamonds", "diamonds", "hearts", 
    "hearts", "hearts", "hearts", "hearts", "hearts", "hearts", "hearts", 
    "hearts", "hearts", "hearts", "hearts", "hearts"), 
  value = c(13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 13, 12, 11, 10, 9, 8, 
    7, 6, 5, 4, 3, 2, 1, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 13, 12, 11, 
    10, 9, 8, 7, 6, 5, 4, 3, 2, 1),
  stringsAsFactors = FALSE
)
deck
```

```{r}
head(deck)
```

```{r}
write.csv(deck, file = "cards.csv", row.names = FALSE)
```

```{r}
deck[1:2, 1:2]
deck[1:2, 1, drop = FALSE]
```

```{r}
deck[, "value"]
```

```{r}
deck2 <- deck
deck2
```

```{r}
random <- sample(1:52, size = 52)
deck4 <- deck[random, ]
deck4
```

```{r}
shuffle <- function(cards) {
  n <- nrow(cards)
  random <- sample(1:n, size = n)
  cards[random,]
}
shuffle(deck)
```

```{r}
mean(deck$value)
median(deck$value)
lst <- list(numbers = c(1, 2), logical = TRUE, strings = c("a", "b", "c"))
lst
lst$numbers
sum(lst$numbers)
```

```{r}
deck2 <- deck
deck2
```

```{r}
vec <- c(0, 0, 0, 0, 0)
vec
vec[1]
vec[1] <- 1000
vec
vec[c(1, 3, 5)] <- c(1, 1, 1)
vec
vec[7] <- 0
vec
```

```{r}
deck2$new <- 1:52
deck2
deck2$new <- NULL
deck2
```

```{r}
deck2[c(13, 26, 39, 52), ]
deck2[c(13, 26, 39, 52), 3] <- 14
head(deck2, n = 13)

```

```{r}
1 %in% c(3, 4, 5)
c(1, 2, 3) %in% c(3, 4, 5)
deck$face == deck2$face
```

```{r}
deck$face == shuffle(deck2)$face
sum(deck2$face == "ace")
```

```{r}
deck3 <- deck
deck3$value[deck3$face == "ace"] <- 14
deck3
```

```{r}
deck4 <- deck4
deck4$value <- 0
deck4
```

```{r}
a <- c(1, 2, 3)
b <- c(1, 2, 3)
c <- c(1, 2, 4)

a == b
b == c
a == b & b == c
```

```{r}
queen_spades <- deck4$face == "queen" & deck4$suit == "spades"
queen_spades
deck4[queen_spades, ]
```

```{r}
w <- c(-1, 0, 1)
x <- c(5, 15)
y <- "February"
z <- c("Monday", "Tuesday", "Friday")

w > 0
x > 10 & x < 20
y == "February"

```

```{r}
deck5 <- deck
deck5 %>%
  print(n = 13)
```

```{r}
facecard <- deck5$face %in% c("king", "queen", "jack")
deck5[facecard, ] <- 10
deck5 %>% print(n = 13)
```

```{r}
library(magrittr)
v <- c(1, 2, 3, NA)
is.na(v)
#deck5$value[deck5$face == "ace"] <- NA
deck5 <-
  deck5 %>%
  mutate(value = ifelse(face == "ace", NA, value)) %T>%
  print(n = 13)
```



# Chapter 8 -------------------------

```{r}
install.packages("pryr")
library(pryr)
parenvs(all = TRUE)
```

```{r}
as.environment("package:stats")
globalenv()
baseenv()
emptyenv()
```

```{r}
parent.env(globalenv())
```


```{r}
foo <- "take me to your runtime"
show_env <- function(x = foo) {
  list(
    rand.in = environment(),
    parent = parent.env(environment()),
    objects = ls.str(environment())
  )
}
show_env()
```

```{r}
deal <- function() {
  deck[1, ]
}

environment(deal)
deal()
```

```{r}
DECK <- deck
```

```{r}
deal <- function() {
  card <- deck[1, ]
  assign("deck", deck[-1, ], envir = globalenv())
  card
}
```

```{r}
deal()
deck
```

```{r}
shuffle <- function() {
  random <- sample(1:52, size = 52)
  assign("deck", DECK[random, ], envir = globalenv())
}
```

```{r}
DECK <- deck
```

```{r}
shuffle()
deck
```

```{r}
setup <- function(deck) {
  DECK <- deck
  
  DEAL <- function() {
    card <- deck[1, ]
    assign("deck", deck[-1, ], envir = globalenv())
    card
  }
  SHUFFLE <- function() {
    random <- sample(1:52, size = 52)
    assign("deck", DECK[random, ], envir = globalenv())
  }
  list(deal = DEAL, shuffle = SHUFFLE)
}
```

```{r}
cards <- setup(deck)
```

```{r}
cards$shuffle()
cards$deal()
```

```{r}
rm(deck)
```

```{r}
deal()
```

```{r}
DECK
```

```{r}
a <- setup(DECK)
```

```{r}
a$shuffle()
a$deal()
```

```{r}
a$deal()
```


# Part 3 ----------------
## Ch 9

```{r}
get_symbols <- function() {
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  sample(
    wheel, size = 3, replace = TRUE,
    prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52)
  )
}
get_symbols()
```

```{r}
play <- function() {
  symbols <- get_symbols()
  print(symbols)
  score(symbols)
}
```

```{r}
x <- 1
if (3 == 3) {
  x <- 2
}
x
```

```{r}
a = c(FALSE, TRUE)
b = c(TRUE, FALSE)
a && b
```

```{r}
allget_symbols() %in% c("B", "BB", "BBB")
```

```{r}
payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
  "B" = 10, "C" = 10, "0" = 0)
payouts
```

```{r}
unname(payouts["DD"]) 
```

```{r}
# identify case

score <- function(symbols) {
  
  same <- symbols[1] == symbols[2] && symbols[2] == symbols[3]
  bars <- symbols %in% c("B", "BB", "BBB")
  
  # get prize
  if (same) {
    payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
      "B" = 10, "C" = 10, "0" = 0)
    prize <- unname(payouts[symbols[1]])
  } else if (all(bars)) {
    prize <- 5
  } else {
    cherries <- sum(symbols == "C")
    prize <- c(0, 2, 5)[cherries + 1]
  }
  
  # adjust for diamonds
  diamonds <- sum(symbols == "DD")
  prize * 2 ^ diamonds

}

score(get_symbols())
```

```{r}
play <- function() {
  symbols <- get_symbols()
  print(symbols)
  score(symbols)
}
```

```{r}
play()
```


## Ch 10

```{r}
num <- 1000000000
print(num)
class(num) <- c("POSIXct", "POSIXt")
print(num)
```

```{r}
attributes(deck)
str(deck)
```

```{r}
row.names(deck)
row.names(deck) <- 101:152
levels(deck) <- c("L1", "L2", "L3")
attributes(deck)
```

```{r}
play <-
```

