---
title: "R Notebook"
output: html_notebook
---


```{r}
plot(mtcars$wt, mtcars$mpg)

library(tidyverse)
qplot(mtcars$wt, mtcars$mpg)
```

```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point()
```


```{r}
plot(pressure$temperature, pressure$pressure, type = "l")
points(pressure$temperature, pressure$pressure)
lines(pressure$temperature, pressure$pressure / 2, col = "red")
points(pressure$temperature, pressure$pressure / 2, col = "red")
```

```{r}
qplot(pressure$temperature, pressure$pressure, geom = "line")
ggplot(pressure, aes(x = temperature, y = pressure)) + geom_line()
```

```{r}
qplot(temperature, pressure, data = pressure, geom = c("line", "point"))
ggplot(pressure, aes(x = temperature, y = pressure)) + geom_line() + geom_point()
```

```{r}
barplot(BOD$demand, names.arg=BOD$Time)
barplot(table(mtcars$cyl))
```

```{r}
qplot(factor(mtcars$cyl))
```

```{r}
ggplot(BOD, aes(x = factor(Time), y = demand)) + geom_bar(stat = "identity")
```

```{r}
qplot(factor(cyl), data = mtcars)
ggplot(mtcars, aes(x=factor(cyl))) + geom_bar()
```

```{r}
hist(mtcars$mpg, breaks = 10)
ggplot(mtcars, aes(x = mpg)) + geom_histogram(binwidth = 4)
```

```{r}
plot(ToothGrowth$supp, ToothGrowth$len)
boxplot(len ~ supp, data = ToothGrowth)
qplot(ToothGrowth$supp, ToothGrowth$len, geom="boxplot")
ggplot(ToothGrowth, aes(x = supp, y = len)) + geom_boxplot()
```

```{r}
qplot(interaction(ToothGrowth$supp, ToothGrowth$dose), ToothGrowth$len,
          geom="boxplot")
```


```{r}
curve(x ^ 3 - 5 * x, from = -4, to = 4)
myfun <- function(xvar) {
  1 / (1 + exp(-xvar + 10))
}
curve(myfun(x), from = 0, to = 20)
curve(1 - myfun(x), add = TRUE, col = "red")

ggplot(data.frame(x=c(0, 20)), aes(x=x)) + 
  stat_function(fun=myfun, geom="line")
```


```{r}
BOD
str(BOD)
ggplot(BOD, aes(x=Time, y=demand)) + 
  geom_bar(stat="identity")
ggplot(BOD, aes(x = factor(Time), y = demand)) + 
  geom_bar(stat = "identity")

ggplot(BOD, aes(x = Time, y = demand)) +
  geom_bar(stat = "identity", fill = "lightblue", color = "black")
```

```{r}
library(gcookbook)
cabbage_exp
```

```{r}
ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
  geom_bar(stat = "identity", position="dodge")
ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
  geom_bar(stat = "identity", position="dodge", colour="black") +
  scale_fill_brewer(palette="Pastel1")
```

```{r}
ce <- cabbage_exp[1:5, ]
ce
ggplot(ce, aes(x=Date, y=Weight, fill=Cultivar)) +
    geom_bar(stat = "identity", position="dodge", colour="black") +
    scale_fill_brewer(palette="Pastel1")
```

```{r}
ggplot(diamonds, aes(x=cut)) + geom_bar()
ggplot(diamonds, aes(x=carat)) + geom_bar(binwidth = 0.15)
```

```{r}
upc <- subset(uspopchange, rank(Change)>40)
upc
```

```{r}
rank(uspopchange$Change)
ggplot(upc, aes(x=Abb, y=Change, fill=Region)) +
  scale_fill_manual(values=c("#669933", "#FFCC66")) +
  geom_bar(stat="identity")
```

```{r}
upc
```

```{r}
csub <- subset(climate, Source == "Berkeley" & Year >= 1900)
csub$pos <- csub$Anomaly10y >= 0
csub
ggplot(csub, aes(x = Year, y = Anomaly10y, fill = pos)) +
  geom_bar(stat="identity", position = "identity")

ggplot(csub, aes(x=Year, y=Anomaly10y, fill=pos)) +
geom_bar(stat="identity", position="identity", colour="black", size=0.25) + scale_fill_manual(values=c("#CCEEFF", "#FFDDDD"), guide=FALSE)
```

```{r}
ggplot(pg_mean, aes(x=group, y=weight)) + geom_bar(stat="identity")
ggplot(pg_mean, aes(x=group, y=weight)) + geom_bar(stat="identity", width=0.5)
ggplot(pg_mean, aes(x=group, y=weight)) + geom_bar(stat="identity", width=1)
ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
  geom_bar(stat="identity", width=0.5, position="dodge")
ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
  geom_bar(stat="identity", width=0.5, position=position_dodge(0.7))
```

```{r}
ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
geom_bar(stat="identity")
```

```{r}

    # Below the top
    ggplot(cabbage_exp, aes(x=interaction(Date, Cultivar), y=Weight)) +
        geom_bar(stat="identity") +
        geom_text(aes(label=Weight), vjust=1.5, colour="white")
    # Above the top
    ggplot(cabbage_exp, aes(x=interaction(Date, Cultivar), y=Weight)) +
        geom_bar(stat="identity") +
        geom_text(aes(label=Weight), vjust=-0.2)
    # Adjust y limits to be a little higher
    ggplot(cabbage_exp, aes(x=interaction(Date, Cultivar), y=Weight)) +
        geom_bar(stat="identity") +
        geom_text(aes(label=Weight), vjust=-0.2) +
        ylim(0, max(cabbage_exp$Weight) * 1.05)
    # Map y positions slightly above bar top - y range of plot will auto-adjust
    ggplot(cabbage_exp, aes(x=interaction(Date, Cultivar), y=Weight)) +
        geom_bar(stat="identity") +
        geom_text(aes(y=Weight+0.1, label=Weight))
   ggplot(cabbage_exp, aes(x=Date, y=Weight, fill=Cultivar)) +
        geom_bar(stat="identity", position="dodge") +
        geom_text(aes(label=Weight), vjust=1.5, colour="white",
                  position=position_dodge(.9), size=3)

```
```{r}
tophit <- tophitters2001[1:25,]
ggplot(tophit, aes(x = avg, y = reorder(name, avg))) + 
  geom_point(size = 3) + # Use a larger dot theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(colour = "grey60", linetype = "dashed")
  )

ggplot(tophit, aes(x = avg, y = reorder(name, avg))) + 
  geom_point(size = 3) + # Use a larger dot theme_bw() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_line(colour = "grey60", linetype = "dashed")
  )
ggplot(tophit, aes(x = reorder(name, avg), y = avg)) + 
  geom_point(size = 3) + # Use a larger dot theme_bw() + 
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_line(colour = "grey60", linetype = "dashed")
  )
```

```{r}
ggplot(BOD, aes(x = Time, y = demand)) + geom_line()
```

```{r}
BOD
BOD$demand2 <- BOD$demand / 2
BOD1 <- BOD
BOD
BOD1$Time <- factor(BOD1$Time)
ggplot(BOD1) + 
  geom_line(aes(x = Time, y = demand, group = 1)) + 
  geom_line(aes(x = Time, y = demand2, group = 2)) +
  expand_limits(y = 0)
```

```{r}
ggplot(BOD, aes(x = Time, y = demand)) + geom_line() + geom_point()
```

```{r}
ggplot(worldpop, aes(x = Year, y = Population)) + 
  geom_line() +
  geom_point() +
  scale_y_log10()
```

```{r}
tg <- ToothGrowth %>% group_by(supp, dose) %>% summarise(length = mean(len))
ggplot(tg, aes(x = dose, y = length, colour = supp)) + geom_line()
```

```{r}
ggplot(tg, aes(x=dose, y=length, fill=supp)) + geom_line() + geom_point(size=4, shape=21)
```

```{r}
ggplot(BOD, aes(x = Time, y = demand)) + geom_line(linetype="dashed", size = 2, color = "blue")
```

```{r}
ggplot(tg, aes(x=dose, y=length, colour=supp)) +
        geom_line() +
        scale_colour_brewer(palette="Set1")
```

```{r}
ggplot(tg, aes(x=dose, y=length, group=supp)) +
  geom_line(colour="darkgreen", size=1.5)
ggplot(tg, aes(x=dose, y=length, colour=supp)) +
  geom_line(linetype="dashed") +
  geom_point(shape=22, size=3, fill="white")

```

```{r}
ggplot(BOD, aes(x=Time, y=demand)) +
  geom_line() +
  geom_point(size=4, shape=22, colour="darkred", fill="pink")

ggplot(BOD, aes(x=Time, y=demand)) +
  geom_line() +
  geom_point(size=4, shape=21, fill="white")
ggplot(tg, aes(x=dose, y=length, fill=supp)) +
    geom_line() +
    geom_point(shape=21, size=3) +
    scale_fill_manual(values=c("red","pink"))
```

```{r}
sunspotyear <- data.frame(
  Year = as.numeric(time(sunspot.year)),
  Sunspots = as.numeric(sunspot.year))
sunspotyear
ggplot(sunspotyear, aes(x = Year, y = Sunspots)) + 
  geom_area(colour="black", fill="blue", alpha=.2)


```

```{r}
uspopage
```

```{r}
ggplot(uspopage, aes(x=Year, y=Thousands, fill=AgeGroup, order=desc(AgeGroup))) + geom_area(colour=NA, alpha=.4) +
scale_fill_brewer(palette="Blues") +
geom_line(position="stack", size=.2)
```

```{r}
uspopage_prop <- uspopage %>% 
  group_by(Year) %>% 
  mutate(Percent = Thousands / sum(Thousands) * 100)
uspopage_prop
ggplot(uspopage_prop, aes(x=Year, y=Percent, fill=AgeGroup, order=desc(AgeGroup))) +
  geom_area(color="black", size=.2, alpha=.4) +
  scale_fill_brewer(palette="Blues", breaks=(levels(uspopage$AgeGroup)))

```

```{r}
clim <- climate %>% filter(Source == "Berkeley") %>% select(Year, Anomaly10y, Unc10y)
clim
```

```{r}
ggplot(clim, aes(x=Year, y=Anomaly10y)) + 
    geom_ribbon(aes(ymin = Anomaly10y-Unc10y, ymax = Anomaly10y+Unc10y), alpha=0.2) +
  geom_line() 
```

```{r}
ggplot(clim, aes(x=Year, y=Anomaly10y)) +
        geom_line(aes(y=Anomaly10y-Unc10y), colour="grey50", linetype="dotted") +
        geom_line(aes(y=Anomaly10y+Unc10y), colour="grey50", linetype="dotted") +
        geom_line()
```

```{r}
heightweight %>% select(sex, ageYear, heightIn)
ggplot(heightweight, aes(x=ageYear, y=heightIn)) + geom_point()
ggplot(heightweight, aes(x=ageYear, y=heightIn)) + geom_point(shape=19)
ggplot(heightweight, aes(x=ageYear, y=heightIn)) + geom_point(size=2)
ggplot(heightweight, aes(x=ageYear, y=heightIn, colour=sex)) + geom_point()
ggplot(heightweight, aes(x=ageYear, y=heightIn, shape=sex, color=sex)) + geom_point()
```

```{r}

    ggplot(heightweight, aes(x=ageYear, y=heightIn, shape=sex, colour=sex)) +
        geom_point() +
        scale_shape_manual(values=c(1,2)) +
        scale_colour_brewer(palette="Set1")
```

```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn)) +
        geom_point( size=3)
```

```{r}
hw <- heightweight
#hw$weightLb <- 
hw %>% select(weightLb) %>% cut(breaks = c(-Inf, 100, Inf), labels = c("<100", ">=100"))
```

```{r}
cut(hw$weightLb, breaks = c(-Inf, 100, Inf), labels = c("<100", ">=100"))
```
```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, size=weightLb)) + geom_point()
ggplot(heightweight, aes(x=weightLb, y=heightIn, fill=ageYear)) +
geom_point(shape=21, size=2.5) +
scale_fill_gradient(low="black", high="white")
ggplot(heightweight, aes(x=weightLb, y=heightIn, fill=ageYear)) +
geom_point(shape=21, size=2.5) +
scale_fill_gradient(low="black", high="white", breaks=12:17,
guide=guide_legend())

```

```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, size=weightLb, colour=sex)) +
  geom_point(alpha=.5)
ggplot(heightweight, aes(x=ageYear, y=heightIn, size=weightLb, colour=sex)) +
  geom_point(alpha=.5) + scale_size_area() +
  scale_color_brewer(palette = "Set1")
```

```{r}
sp <- ggplot(diamonds, aes(x = carat, y = price))
sp + geom_point()
sp + geom_point(alpha = 0.01)
```

```{r}
library(hexbin)
sp + stat_bin_hex() +
      scale_fill_gradient(low="lightblue", high="red",
                            breaks=c(0, 250, 500, 1000, 2000, 4000, 6000),
                            limits=c(0, 6000))

```

```{r}
ChickWeight
sp1 <- ggplot(ChickWeight, aes(x = Time, y = weight))
sp1 + geom_point()
sp1 + geom_point(position = "jitter")
sp1 + geom_boxplot(aes(group=Time))
```

```{r}
sp <- ggplot(heightweight, aes(x = ageYear, y = heightIn))
sp + geom_point(color = "grey60") + stat_smooth(method = lm)
sp + geom_point() + stat_smooth(method=loess)
```

```{r}
library(MASS)
b <- biopsy
b$classn[b$class=="benign"]    <- 0
b$classn[b$class=="malignant"] <- 1

ggplot(b, aes(x=V1, y=classn)) +
  geom_point(position=position_jitter(width=0.3, height=0.06), 
             alpha=0.4, shape=21, size=1.5) + 
  stat_smooth(method=glm, family=binomial)
```

```{r}
 sps <- ggplot(heightweight, aes(x=ageYear, y=heightIn, colour=sex)) +
           geom_point() +
           scale_colour_brewer(palette="Set1")
    sps + geom_smooth(method = loess)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

